Repository flipt-io/flipt, pull requests merged in 2022-11, with the labels that each got.

#1128 feat: authentication service
  internal/containers/option.go
  internal/server/auth/method/token/server.go
  internal/server/auth/middleware_test.go
  internal/server/auth/server.go
  internal/server/auth/server_test.go
  internal/storage/auth/auth.go
  internal/storage/auth/bootstrap.go
  internal/storage/auth/memory/store.go
  internal/storage/auth/memory/store_test.go
  internal/storage/auth/sql/store.go
  internal/storage/auth/sql/store_test.go
  internal/storage/auth/testing/testing.go
  internal/storage/storage.go
  internal/storage/testing/testing.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/auth/auth_grpc.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
  rpc/flipt/flipt.yaml
  swagger/auth/auth.swagger.json
Labels: auth

#1158 chore: setup nightly builds, allow for pre-release builds
  .github/workflows/nightly.yml
  .goreleaser.yml
Labels: size/M

#1159 Revert "chore: setup nightly builds, allow for pre-release builds"
  .github/workflows/nightly.yml
  .goreleaser.yml
Labels: size/M

#1160 chore: nightly builds
  .github/workflows/nightly.yml
  .goreleaser.yml
Labels: size/L

#1162 chore: add nightly builds section to README
  .github/workflows/nightly.yml
  README.md
Labels: size/S

#1175 fix(auth): mount core auth service via grpc gateway
  cmd/flipt/main.go
  internal/server/middleware/grpc/middleware.go
  test/api.sh
  test/api_with_auth.sh
  test/config/test.yml
Labels: size/M

#1176 fix(auth): [release/1.15] mount core auth service via grpc gateway (#1175)
  .github/actions/integration-test/action.yml
  .github/workflows/integration-test-image.yml
  .github/workflows/integration-test.yml
  CHANGELOG.md
  Dockerfile.it
  cmd/flipt/main.go
  internal/server/middleware.go
  test/api.sh
  test/api_with_auth.sh
  test/config/test.yml
  test/ui.sh
Labels: size/L

#1173 Change test case to show the correct format of multi domains for CORS
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
Labels: size/XS

#1179 fix(config/cors): use strings.Fields for string to string slice fields
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
Labels: size/S

#1177 chore: update README with additional client SDKs
  README.md
Labels: size/S

#1180 fix(config/cors): [release/1.15] use strings.Fields for string to string slice fields (#1179)
  CHANGELOG.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
Labels: size/M

#1181 fix(config/cors): [release/1.4] use strings.Fields for string to string slice fields (#1179)
  CHANGELOG.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
Labels: size/M

#1182 chore: only tag/push latest Docker for latest semantic tag
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .goreleaser.nightly.yml
  .goreleaser.yml
Labels: size/M

#1183 fix(sql/testing): use wait.ForSQL when readying cockroach
  internal/storage/sql/testing/testing.go
Labels: size/S

#1161 feat(authentication): per method cleanup process
  cmd/flipt/main.go
  config/migrations/cockroachdb/2_create_table_operation_lock.down.sql
  config/migrations/cockroachdb/2_create_table_operation_lock.up.sql
  config/migrations/mysql/3_create_table_operation_lock.down.sql
  config/migrations/mysql/3_create_table_operation_lock.up.sql
  config/migrations/postgres/5_create_table_operation_lock.down.sql
  config/migrations/postgres/5_create_table_operation_lock.up.sql
  config/migrations/sqlite3/5_create_table_operation_lock.down.sql
  config/migrations/sqlite3/5_create_table_operation_lock.up.sql
  errors/errors.go
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/errors.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/authentication/negative_interval.yml
  internal/config/testdata/authentication/zero_grace_period.yml
  internal/storage/auth/memory/store.go
  internal/storage/auth/testing/testing.go
  internal/storage/oplock/memory/memory.go
  internal/storage/oplock/memory/memory_test.go
  internal/storage/oplock/oplock.go
  internal/storage/oplock/sql/sql.go
  internal/storage/oplock/sql/sql_test.go
  internal/storage/oplock/testing/testing.go
  internal/storage/sql/migrator.go
  internal/storage/sql/testing/testing.go
Labels: size/XL

#1185 chore: update to use goreleaser-pro for snapshot build
  .github/workflows/snapshot.yml
Labels: size/XS

#1184 feat: release v1.16.0
  CHANGELOG.md
Labels: size/S
