Repository flipt-io/flipt, pull requests merged in 2022-12, with the labels that each got.

#1187 chore: try to fix latest tag/push on release
  .github/workflows/release.yml
Labels: size/XS

#1188 fix: dont print to stdout using color/non json formatted output when running with JSON output logger
  cmd/flipt/main.go
Labels: size/S

#1198 feat(gh): add workflow to trigger grpc client update
  .github/workflows/release-clients.yml
Labels: size/M

#1199 chore(gh): deploy latest version of try.flipt.io after flipt release
  .github/workflows/post-release.yml
Labels: size/S

#1196 chore(config): add Json/Cue schema
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/log.go
  test/api.sh
Labels: size/XL

#1204 chore(config): add yaml-lang-server annotations to configs
  config/default.yml
  config/local.yml
  config/production.yml
Labels: size/XS

#1200 feat: trigger update ruby grpc job on release
  .github/workflows/release-clients.yml
Labels: size/XS

#1213 chore(build): fix nightly/all builds to install gcc
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: size/XS

#1139 feat(server/auth): validate flipt_client_token cookie in middleware
  internal/server/auth/middleware.go
  internal/server/auth/middleware_test.go
Labels: size/L

#1138 feat(rpc/auth): add OIDC auth method service gRPC definition
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/auth/auth_grpc.pb.go
  rpc/flipt/flipt.yaml
  swagger/auth/auth.swagger.json
Labels: automerge, size/L

#1216 refactor(main): move grpc and http composition into internal/cmd
  cmd/flipt/main.go
  errors/errors.go
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/cmd/auth.go
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/gateway/gateway.go
  internal/server/auth/method/token/server.go
  internal/server/auth/server.go
  internal/server/server.go
  internal/storage/oplock/testing/testing.go
  internal/storage/sql/errors.go
  internal/storage/sql/testing/testing.go
Labels: size/XXL

#1223 feat(oidc): support generic OIDC providers
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/server/auth/method/oidc/http.go
  internal/server/auth/method/oidc/server.go
  internal/server/auth/method/oidc/server_test.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  swagger/auth/auth.swagger.json
Labels: size/L

#1226 chore: refactor deprecations checking to own method
  go.mod
  go.sum
  internal/config/authentication.go
  internal/config/cache.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/cors.go
  internal/config/database.go
  internal/config/deprecate.go
  internal/config/deprecations.go
  internal/config/log.go
  internal/config/meta.go
  internal/config/server.go
  internal/config/tracing.go
  internal/config/ui.go
Labels: size/L

#1224 chore: move migrator back to main so we dont need it in grpc server
  cmd/flipt/main.go
  internal/cmd/grpc.go
Labels: size/S

#1227 feat: deprecate ui enabled
  CHANGELOG.md
  DEPRECATIONS.md
  cmd/flipt/main.go
  internal/config/cache.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/deprecated/ui_disabled.yml
  internal/config/ui.go
Labels: size/L

#1225 feat: support config versioning
  config/default.yml
  config/flipt.schema.cue
  config/flipt.schema.json
  config/local.yml
  config/production.yml
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/version/invalid.yml
  internal/config/testdata/version/v1.yml
Labels: size/M

#1197 feat(auth/oidc): OIDC authentication method support
  errors/errors.go
  go.mod
  go.sum
  internal/cmd/auth.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
  internal/server/auth/method/oidc/http.go
  internal/server/auth/method/oidc/server.go
  internal/server/auth/method/oidc/server_test.go
  internal/server/auth/method/oidc/testing/grpc.go
  internal/server/auth/method/oidc/testing/http.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  swagger/auth/auth.swagger.json
  ui/vite.config.js
Labels: size/XXL

#1240 feat(auth): public list authentication methods endpoint
  internal/cleanup/cleanup_test.go
  internal/cmd/auth.go
  internal/cmd/http.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/server/auth/method/oidc/server.go
  internal/server/auth/method/oidc/server_test.go
  internal/server/auth/public/server.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/auth/auth_grpc.pb.go
  rpc/flipt/flipt.yaml
  swagger/auth/auth.swagger.json
  test/api.sh
  test/config/test-with-auth.yml
Labels: size/L

#1241 chore: rm swagger (openapiv2) self hosted api docs in favor of public api docs
  README.md
  buf.gen.yaml
  codecov.yml
  internal/cmd/http.go
  swagger/auth/auth.swagger.json
  swagger/embed.go
  swagger/flipt.swagger.json
  swagger/index.html
  ui/src/components/Nav.vue
  ui/vite.config.js
Labels: size/XXL

#1242 feat(auth): add arbitrary list methods metadata field
  internal/config/authentication.go
  internal/server/auth/public/server.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
Labels: size/S
