Repository flipt-io/flipt, pull requests merged in 2022-10, with the labels that each got.

#1083 refactor(server): move server package to internal
  .github/workflows/filtered-github-webhooks.yml
  cmd/flipt/main.go
  internal/server/cache/cache.go
  internal/server/cache/memory/cache.go
  internal/server/cache/memory/cache_test.go
  internal/server/cache/metrics.go
  internal/server/cache/redis/cache.go
  internal/server/cache/redis/cache_test.go
  internal/server/evaluator.go
  internal/server/evaluator_test.go
  internal/server/flag.go
  internal/server/flag_test.go
  internal/server/metrics.go
  internal/server/middleware.go
  internal/server/middleware_test.go
  internal/server/rule.go
  internal/server/rule_test.go
  internal/server/segment.go
  internal/server/segment_test.go
  internal/server/server.go
  internal/server/support_test.go
Labels: chore

#1093 feat(rpc): define auth protobuf package and Authentication model
  buf.gen.yaml
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
  swagger/auth/auth.swagger.json
Labels: auth

#1098 fix(migrations/sqlite3): syntax error in uniqueness constraint on temp table in down operation
  config/migrations/sqlite3/1_variants_unique_per_flag.down.sql
Labels: bug
