Repository flipt-io/flipt, pull requests merged in 2023-10, with the labels that each got.

#2257 feat: impl grpc health check
  go.work.sum
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/server/metadata/server.go
  rpc/flipt/flipt.yaml
Labels: needs docs

#2272 feat(git): support SSH authentication
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.work.sum
  internal/cmd/grpc.go
  internal/config/config_test.go
  internal/config/storage.go
  internal/config/testdata/storage/git_ssh_auth_invalid_missing_password.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_private_key_both.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_private_key_missing.yml
  internal/config/testdata/storage/git_ssh_auth_valid_with_path.yml
Labels: needs docs

#2290 chore: tests were broken because of this fixed it up
  internal/storage/fs/snapshot_test.go
Labels: automerge

#2299 feat: add subject to authentication metadata for auditing
  internal/server/auth/method/github/server.go
  internal/server/auth/method/github/server_test.go
  internal/server/auth/method/oidc/server.go
  internal/server/auth/method/oidc/server_test.go
  internal/server/auth/server.go
Labels: automerge, needs docs

#2318 feat: add flag key to variant and boolean evaluation responses
  build/testing/integration/api/api.go
  build/testing/integration/readonly/readonly_test.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_test.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.proto
Labels: automerge
