Repository flipt-io/flipt, pull requests merged in 2023-07, with the labels that each got.

#1811 fix: Fix validate command
  cmd/flipt/validate.go
  internal/cue/fixtures/invalid.yaml
  internal/cue/validate.go
  internal/cue/validate_test.go
Labels: size/L

#1812 chore: add feedback link to app footer
  README.md
  ui/src/components/Footer.tsx
Labels: size/M

#1813 chore: Labs link
  .github/images/labs.png
  README.md
Labels: size/S

#1822 chore: use common aliases for flipt/errors pkg
  internal/storage/fs/snapshot.go
  internal/storage/sql/common/util.go
  internal/storage/sql/errors.go
Labels: size/M

#1821 chore: Pre commit hook
  .pre-commit-config.yaml
  DEVELOPMENT.md
Labels: size/S

#1806 feat: v2 evaluate boolean
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_store_mock.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/evaluator.go
  internal/server/evaluation/evaluator_mock.go
  internal/server/evaluation/evaluator_test.go
  internal/server/evaluation/server.go
  internal/server/middleware/grpc/support_test.go
  internal/server/server.go
  internal/server/support_test.go
  internal/storage/fs/snapshot.go
  internal/storage/sql/common/evaluation.go
  internal/storage/storage.go
  rpc/flipt/evaluation/evaluation.go
Labels: size/XL

#1805 fix(api/rollouts): ensure tx rollback
  build/internal/flipt.go
  build/testing/integration.go
  build/testing/integration/api/api.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/default.yaml
  build/testing/integration/readonly/testdata/production.yaml
  internal/storage/sql/common/rollout.go
  internal/storage/sql/rollout_test.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/validation.go
Labels: size/L

#1825 chore: Update post-release.yml
  .github/workflows/post-release.yml
  .goreleaser.yml
Labels: size/XS

#1827 refactor!(rpc/flipt): rename RolloutPercentage to RolloutThreshold
  build/testing/integration/api/api.go
  config/migrations/sqlite3/10_rollouts.up.sql
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/evaluator.go
  internal/storage/sql/common/rollout.go
  internal/storage/sql/rollout_test.go
  internal/storage/storage.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
Labels: size/L

#1828 fix: support variant desc in cue import schema
  internal/cue/fixtures/valid.yaml
  internal/cue/flipt.cue
  internal/ext/importer_test.go
  internal/ext/testdata/import.yml
  internal/ext/testdata/import_no_attachment.yml
Labels: size/XS

#1808 chore: add batch evaluation functionality
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_test.go
  rpc/flipt/evaluation/evaluation.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.proto
Labels: size/L

#1830 feat(ui): add flag type radio
  ui/src/app/flags/EditFlag.tsx
  ui/src/app/flags/variants/Variants.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/types/Flag.ts
Labels: size/L

#1831 fix: potential panic in validate
  internal/cue/testdata/fuzz/FuzzValidate/9d39dbf6febda3de
  internal/cue/testdata/invalid.yaml
  internal/cue/testdata/valid.yaml
  internal/cue/validate.go
  internal/cue/validate_fuzz_test.go
  internal/cue/validate_test.go
  internal/ext/exporter_test.go
  internal/ext/importer_fuzz_test.go
Labels: size/M

#1832 chore: v1.23.3
  CHANGELOG.md
Labels: size/S

#1829 chore: implement storage queries for rollout evaluation
  build/testing/integration/api/api.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/evaluator.go
  internal/storage/sql/common/evaluation.go
  internal/storage/sql/evaluation_test.go
  internal/storage/storage.go
Labels: size/L

#1835 feat: create eval rollout threshold
  ui/src/app/flags/EditFlag.tsx
  ui/src/app/flags/Evaluation.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/rollouts/Rollouts.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/TabBar.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/forms/Combobox.tsx
  ui/src/components/forms/Select.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rollouts/rules/ThresholdRuleForm.tsx
  ui/src/components/rules/EditRuleForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/distributions/SingleDistributionForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/data/api.ts
  ui/src/types/Constraint.ts
  ui/src/types/Flag.ts
  ui/src/types/Rollout.ts
  ui/src/types/Variant.ts
Labels: size/XL

#1837 fix(ui): memoize selectors for namespaces
  ui/src/app/namespaces/namespacesSlice.ts
Labels: size/M

#1838 fix: broken ui build
  ui/src/app/console/Console.tsx
Labels: size/S

#1834 feat: add audit logging for rollout actions
  internal/server/audit/audit.go
  internal/server/audit/types.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
Labels: size/L

#1836 feat(rollouts): Add FS store implementation of rollouts
  build/testing/integration/readonly/readonly_test.go
  internal/server/rollout.go
  internal/storage/fs/fixtures/fswithindex/prod/prod.features.yml
  internal/storage/fs/fixtures/fswithindex/sandbox/sandbox.features.yaml
  internal/storage/fs/fixtures/fswithoutindex/prod/features.yml
  internal/storage/fs/fixtures/fswithoutindex/prod/prod.features.yaml
  internal/storage/fs/fixtures/fswithoutindex/staging/features.yml
  internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/features.yaml
  internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/sandbox.features.yml
  internal/storage/fs/fixtures/fswithoutindex/staging/staging.features.yaml
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  internal/storage/fs/sync.go
  internal/storage/sql/common/rollout.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/rollout_test.go
Labels: size/XL
