Repository flipt-io/flipt, pull requests merged in 2023-05, with the labels that each got.

#1568 feat: modify events to return more information about entity during auditing
  Dockerfile
  build/internal/flipt.go
  examples/audit/README.md
  examples/audit/docker-compose.yml
  internal/server/audit/audit.go
  internal/server/audit/audit_test.go
  internal/server/audit/types.go
  internal/server/audit/types_test.go
  internal/server/auth/server.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
Labels: automerge, size/XL

#1567 chore: update changelog for 1.21 release
  CHANGELOG.md
  CODE_OF_CONDUCT.md
Labels: size/S

#1573 chore: add Loki to audit logs example
  examples/audit/.gitignore
  examples/audit/README.md
  examples/audit/docker-compose.yml
  examples/audit/promtail.yml
  examples/images/logos/loki.svg
  examples/images/loki.png
Labels: size/L

#1574 chore: Update .goreleaser.nightly.yml
  .goreleaser.nightly.yml
Labels: size/S

#1577 chore: try again to fix the nightly build (those v's)
  .goreleaser.yml
Labels: size/S

#1572 feat(fs-backend): Use cue to validate against yaml files
  cmd/flipt/main.go
  cmd/flipt/validate.go
  cue/fixtures/invalid.yaml
  cue/fixtures/valid.yaml
  cue/flipt.cue
  cue/validate.go
  cue/validate_test.go
  go.mod
  go.sum
  internal/storage/fs/snapshot.go
Labels: size/L

#1582 chore: make sdk integrations nicer to view on README
  README.md
Labels: size/M

#1584 fix(storage/sql): paginated walk for resources using joins
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/seed.yaml
  internal/storage/sql/common/flag.go
  internal/storage/sql/common/rule.go
  internal/storage/sql/common/segment.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/rule_test.go
  internal/storage/sql/segment_test.go
  internal/storage/sql/testing/testing.go
Labels: size/XXL

#1587 Release/1.21.1
  CHANGELOG.md
Labels: size/S

#1588 feat(ui): add optional constraint description
  ui/index.dev.html
  ui/index.html
  ui/src/app/flags/EditFlag.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/types/Constraint.ts
  ui/vite.config.ts
Labels: size/L

#1599 feat: allow specifying exit code for validation failures
  cmd/flipt/validate.go
  go.work.sum
  internal/cue/fixtures/invalid.yaml
  internal/cue/fixtures/valid.yaml
  internal/cue/flipt.cue
  internal/cue/validate.go
  internal/cue/validate_test.go
  internal/storage/fs/snapshot.go
Labels: size/L

#1601 chore: increasing test coverage to 80%
  internal/server/audit/audit_test.go
  internal/server/auth/server_test.go
  internal/storage/auth/auth_test.go
  internal/storage/auth/bootstrap_test.go
  internal/storage/sql/fields_test.go
Labels: size/L

#1614 Fix db telemetry
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
Labels: size/M

#1612 feat: add text and json format option for output on `flipt validate` command
  cmd/flipt/validate.go
  internal/cue/validate.go
Labels: size/M

#1628 chore(deps): update all otel metrics related packages
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/metrics/metrics.go
  internal/server/cache/metrics.go
  internal/server/evaluator.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
Labels: automerge, size/L

#1602 feat: Datetime constraint
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/testing/integration.go
  build/testing/ui.go
  go.mod
  go.sum
  go.work.sum
  internal/server/evaluator.go
  internal/server/evaluator_test.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
  rpc/flipt/validation.go
  rpc/flipt/validation_test.go
  ui/package-lock.json
  ui/package.json
  ui/playwright.config.ts
  ui/src/App.tsx
  ui/src/app/Layout.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/app/settings/Settings.tsx
  ui/src/app/settings/general/Preferences.tsx
  ui/src/app/settings/namespaces/Namespaces.tsx
  ui/src/components/Header.tsx
  ui/src/components/PreferencesProvider.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/header/Notifications.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/components/notifications/ErrorNotification.tsx
  ui/src/components/notifications/SuccessNotification.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/data/hooks/timezone.ts
  ui/src/types/Constraint.ts
  ui/src/types/Preferences.ts
  ui/tests/namespaces.spec.ts
  ui/tests/preferences.spec.ts
Labels: size/XL

#1645 feat: add namespace to export, check for match on import
  build/testing/integration.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/seed.yaml
  cmd/flipt/export.go
  cmd/flipt/import.go
  internal/ext/common.go
  internal/ext/exporter.go
  internal/ext/importer.go
  internal/ext/importer_fuzz_test.go
  internal/ext/importer_test.go
  internal/ext/testdata/export.yml
  internal/ext/testdata/import_invalid_version.yml
  rpc/flipt/flipt.go
Labels: size/L

#1642 feat: Flipt Validate
  cmd/flipt/main.go
  cmd/flipt/validate.go
  go.mod
  go.sum
  internal/cue/fixtures/invalid.yaml
  internal/cue/fixtures/valid.yaml
  internal/cue/flipt.cue
  internal/cue/validate.go
  internal/cue/validate_test.go
Labels: size/L

#1654 fix(storage/sql): handle null description on constraint during GetSegment
  internal/storage/sql/common/segment.go
  internal/storage/sql/segment_test.go
Labels: automerge, size/M

#1658 fix: panic if no import file name provided
  cmd/flipt/import.go
Labels: size/XS

#1666 chore: fix telemetry typo; add build to codecov ignore
  codecov.yml
  examples/audit/docker-compose.yml
  examples/authentication/dex/docker-compose.yml
  examples/authentication/proxy/docker-compose.yml
  examples/basic/docker-compose.yml
  examples/database/cockroachdb/docker-compose.yml
  examples/database/mysql/docker-compose.yml
  examples/database/postgres/docker-compose.yml
  examples/metrics/docker-compose.yml
  examples/nextjs/docker-compose.yml
  examples/openfeature/docker-compose.yml
  examples/redis/docker-compose.yml
  examples/tracing/jaeger/docker-compose.yml
  examples/tracing/otlp/docker-compose.yml
  examples/tracing/zipkin/docker-compose.yml
Labels: size/S

#1665 fix: Get the openfeature example working
  examples/openfeature/flipt.db
  examples/openfeature/go.mod
  examples/openfeature/go.sum
  examples/openfeature/main.go
Labels: automerge, size/L

#1646 chore: Simpler dev
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/welcome-message.txt
  DEVELOPMENT.md
  Dockerfile
  README.md
  docker-compose.yml
  magefile.go
  ui/.dockerignore
  ui/Dockerfile
  ui/index.dev.html
  ui/index.html.tmpl
  ui/vite.config.ts
Labels: size/L
