Repository flipt-io/flipt, pull requests merged in 2023-06, with the labels that each got.

#1677 feat(build/testing): mage dagger integration test filtering
  .github/workflows/integration-test.yml
  build/go.mod
  build/go.sum
  build/internal/flipt.go
  build/internal/generate/main.go
  build/internal/ui.go
  build/magefile.go
  build/testing/integration.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/default.yaml
  build/testing/integration/readonly/testdata/production.yaml
  magefile.go
Labels: automerge, size/XXL

#1680 fix: switch namespaces to use Redux
  ui/ARCHITECTURE.md
  ui/package-lock.json
  ui/package.json
  ui/src/App.tsx
  ui/src/app/Layout.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/flags/EditFlag.tsx
  ui/src/app/flags/Evaluation.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/Flags.tsx
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/namespaces/namespacesSlice.ts
  ui/src/app/segments/Segment.tsx
  ui/src/app/segments/Segments.tsx
  ui/src/app/tokens/Tokens.tsx
  ui/src/components/DeletePanel.tsx
  ui/src/components/NamespaceProvider.tsx
  ui/src/components/Nav.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/VariantForm.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/rules/EditRuleForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/components/tokens/ShowTokenPanel.tsx
  ui/src/components/tokens/TokenForm.tsx
  ui/src/components/tokens/TokenTable.tsx
  ui/src/data/hooks/namespace.ts
  ui/src/data/hooks/store.ts
  ui/src/main.tsx
  ui/src/store.ts
  ui/src/types/Meta.ts
Labels: size/XL

#1687 fix: catch errs on call to namespaces API in namespace form
  ui/src/components/namespaces/NamespaceForm.tsx
Labels: size/XS

#1686 chore: update magetask to only install ui deps if change or non-existent
  magefile.go
  ui/.gitignore
Labels: size/S

#1688 chore(deps): update otel dependencies to latest
  go.mod
  go.sum
  go.work.sum
  internal/metrics/metrics.go
  internal/server/cache/metrics.go
  internal/server/metrics/metrics.go
Labels: automerge, size/M

#1685 feat(gitfs): go-git backed implementation of fs.FS
  go.mod
  go.sum
  internal/gitfs/gitfs.go
  internal/gitfs/gitfs_test.go
  internal/gitfs/testdata/four/five/six.txt
  internal/gitfs/testdata/one.txt
  internal/gitfs/testdata/two/three.txt
Labels: size/XL

#1692 Darkmode
  config/local.yml
  go.work.sum
  ui/ARCHITECTURE.md
  ui/index.dev.html
  ui/index.html
  ui/package-lock.json
  ui/package.json
  ui/src/App.tsx
  ui/src/app/Layout.tsx
  ui/src/app/NotFoundLayout.tsx
  ui/src/app/Settings.tsx
  ui/src/app/auth/Login.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/preferences/Preferences.tsx
  ui/src/app/preferences/preferencesSlice.ts
  ui/src/app/segments/Segment.tsx
  ui/src/app/settings/general/Preferences.tsx
  ui/src/components/EmptyState.tsx
  ui/src/components/Header.tsx
  ui/src/components/Modal.tsx
  ui/src/components/Nav.tsx
  ui/src/components/Pagination.tsx
  ui/src/components/PreferencesProvider.tsx
  ui/src/components/Searchbox.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/TabBar.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/VariantForm.tsx
  ui/src/components/forms/Button.tsx
  ui/src/components/forms/Combobox.tsx
  ui/src/components/forms/Input.tsx
  ui/src/components/forms/Listbox.tsx
  ui/src/components/forms/Select.tsx
  ui/src/components/forms/TextArea.tsx
  ui/src/components/forms/Toggle.tsx
  ui/src/components/header/Notifications.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/notifications/ErrorNotification.tsx
  ui/src/components/notifications/SuccessNotification.tsx
  ui/src/components/rules/EditRuleForm.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/distributions/MultiDistributionForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/tokens/ShowTokenPanel.tsx
  ui/src/components/tokens/TokenForm.tsx
  ui/src/data/hooks/timezone.ts
  ui/src/modules.d.ts
  ui/src/store.ts
  ui/src/types/Preferences.ts
  ui/tailwind.config.cjs
Labels: size/XL

#1705 feat(fs/git): Implement `fs.Store` and `git.Source`
  .github/workflows/test.yml
  build/go.mod
  build/go.sum
  build/internal/cmd/gitea/main.go
  build/testing/test.go
  go.mod
  go.sum
  internal/gitfs/gitfs.go
  internal/gitfs/gitfs_test.go
  internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/features.yaml
  internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/sandbox.features.yml
  internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/sandbox.yml
  internal/storage/fs/git/source.go
  internal/storage/fs/git/source_test.go
  internal/storage/fs/git/testdata/features.yml
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  internal/storage/fs/store.go
  internal/storage/fs/store_test.go
  internal/storage/fs/sync.go
Labels: size/XL

#1708 feat(fs/git): install and test fs/git backend
  .github/workflows/integration-test.yml
  build/internal/cmd/generate/main.go
  build/internal/cmd/gitea/main.go
  build/testing/integration.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/.flipt.yml
  build/testing/integration/readonly/testdata/seed.yaml
  internal/cmd/auth.go
  internal/cmd/grpc.go
  internal/config/audit.go
  internal/config/authentication.go
  internal/storage/fs/fixtures/fswithindex/.flipt.yml
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  internal/storage/storage.go
Labels: size/XXL

#1712 feat(config): add support for experimental configuration and features
  build/testing/integration.go
  internal/cmd/grpc.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/experimental.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/storage/git_basic_auth_invalid.yml
  internal/config/testdata/storage/git_provided.yml
  internal/config/testdata/storage/invalid_git_repo_not_specified.yml
  internal/config/testdata/storage/local_provided.yml
Labels: size/M

#1711 feat: add local source with test
  internal/storage/fs/local/source.go
  internal/storage/fs/local/source_test.go
  internal/storage/fs/local/testdata/features.yml
Labels: size/L

#1709 Readonly UI
  ui/src/app/Layout.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/flags/EditFlag.tsx
  ui/src/app/flags/Evaluation.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/Flags.tsx
  ui/src/app/meta/metaSlice.ts
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/app/segments/Segments.tsx
  ui/src/app/tokens/Tokens.tsx
  ui/src/components/DeletePanel.tsx
  ui/src/components/EmptyState.tsx
  ui/src/components/Footer.tsx
  ui/src/components/Header.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/VariantForm.tsx
  ui/src/components/forms/buttons/Button.tsx
  ui/src/components/forms/buttons/DeleteButton.tsx
  ui/src/components/header/Notifications.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/rules/EditRuleForm.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/SortableRule.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/tokens/ShowTokenPanel.tsx
  ui/src/components/tokens/TokenForm.tsx
  ui/src/data/api.ts
  ui/src/store.ts
  ui/src/types/Meta.ts
  ui/tests/flags.spec.ts
  ui/tests/index.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/rules.spec.ts
  ui/tests/segments.spec.ts
  ui/tests/tokens.spec.ts
Labels: ui, size/XXL

#1720 chore: add test for UI theme preferences
  ui/tests/preferences.spec.ts
Labels: size/S

#1717 feat(fs/git): support custom poll interval
  internal/cmd/grpc.go
  internal/config/config_test.go
  internal/config/storage.go
  internal/storage/fs/git/source.go
Labels: automerge, size/S

#1721 fix: cross namespaced constraints
  .golangci.yml
  internal/storage/sql/common/segment.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/segment_test.go
Labels: automerge, size/L

#1719 feat: No toggle readonly
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/forms/Toggle.tsx
  ui/tests/flags.spec.ts
Labels: size/S

#1727 test(cli): ensure user configuration path supported
  build/testing/cli.go
Labels: size/M

#1729 test(integration): ensure public and auth self routes are reachable
  build/testing/integration/api/api.go
  build/testing/integration/api/api_test.go
  build/testing/integration/readonly/readonly_test.go
  internal/cmd/auth.go
Labels: automerge, size/M

#1718 feat: dagger test and fixing of default flipt startup
  build/testing/cli.go
  build/testing/testdata/default.yml
  cmd/flipt/main.go
Labels: size/M

#1731 feat: Copy to namespace
  go.work.sum
  ui/postcss.config.cjs
  ui/src/app/flags/EditFlag.tsx
  ui/src/app/flags/Evaluation.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/namespaces/namespacesSlice.ts
  ui/src/app/segments/Segment.tsx
  ui/src/app/tokens/Tokens.tsx
  ui/src/components/Modal.tsx
  ui/src/components/forms/Dropdown.tsx
  ui/src/components/forms/Listbox.tsx
  ui/src/components/forms/Toggle.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/panels/CopyToNamespacePanel.tsx
  ui/src/components/panels/DeletePanel.tsx
  ui/src/data/api.ts
  ui/src/index.css
  ui/src/types/Icon.ts
  ui/tests/flags.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/segments.spec.ts
  ui/tests/tokens.spec.ts
Labels: automerge, size/XXL

#1737 chore: prep changelog
  CHANGELOG.md
Labels: size/M

#1738 fix: count rules was not taking flagKey into account
  internal/server/middleware/grpc/support_test.go
  internal/server/rule.go
  internal/server/rule_test.go
  internal/server/support_test.go
  internal/storage/fs/snapshot.go
  internal/storage/fs/sync.go
  internal/storage/sql/common/rule.go
  internal/storage/storage.go
Labels: size/M

#1746 chore: fix Dagger UI build as node-18 bumped to a different base image
  build/internal/ui.go
Labels: size/XS

#1751 chore: rm markphelps from auto assignee on issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: automerge, size/XS

#1757 Add tag prefix `v` in release link
  .goreleaser.yml
  ui/src/components/Footer.tsx
Labels: automerge, size/XS

#1753 feat: configure use of prepared statements
  cmd/flipt/server.go
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/auth.go
  internal/cmd/grpc.go
  internal/config/config_test.go
  internal/config/database.go
  internal/storage/auth/sql/store_test.go
  internal/storage/oplock/sql/sql_test.go
  internal/storage/sql/db.go
  internal/storage/sql/db_internal_test.go
  internal/storage/sql/db_test.go
  internal/storage/sql/mysql/mysql.go
  internal/storage/sql/postgres/postgres.go
  internal/storage/sql/sqlite/sqlite.go
Labels: size/L

#1760 chore: Release/1.23.1
  CHANGELOG.md
Labels: size/S

#1754 feat: remove trailing slash from http request if it exists in url
  internal/cmd/http.go
  internal/cmd/http_test.go
Labels: size/M

#1758 test(config): ensure default config passes CUE validation
  config/flipt.schema.cue
  config/schema_test.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/database.go
  internal/config/storage.go
  internal/config/testdata/advanced.yml
Labels: automerge, size/L

#1764 chore: try to fix dependabot failing to update PRs
  .github/.kodiak.toml
  .github/dependabot.yml
  go.work.sum
Labels: size/L

#1774 chore: split proto lint workflow to only run on proto changes
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/proto.yml
  go.work.sum
Labels: size/L

#1763 feat(build): add mage dagger:run test:migration
  .github/workflows/test.yml
  build/magefile.go
  build/testing/migration.go
Labels: automerge, size/M

#1784 fix: prevent overwriting URL struct
  internal/cmd/http.go
Labels: size/XS

#1785 test(integration): ensure all list limits are enforced correctly
  build/testing/integration/readonly/readonly_test.go
Labels: size/XS

#1788 test(config): ensure JSON schema validates the default configuration
  config/flipt.schema.json
  config/schema_test.go
  go.mod
  go.sum
  go.work.sum
Labels: size/L

#1791 chore: remove gitleaks worklow
  .github/workflows/scan.yml
Labels: size/M

#1792 chore: remove extra gitleaks files
  .gitleaks.toml
  .gitleaksignore
Labels: size/XXL

#1787 feat: address `pageToken` logic for server and store
  build/testing/integration/api/api.go
  build/testing/integration/readonly/readonly_test.go
  internal/server/flag.go
  internal/server/flag_test.go
  internal/server/namespace.go
  internal/server/namespace_test.go
  internal/server/rule.go
  internal/server/rule_test.go
  internal/server/segment.go
  internal/server/segment_test.go
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  internal/storage/sql/common/flag.go
  internal/storage/sql/common/namespace.go
  internal/storage/sql/common/rule.go
  internal/storage/sql/common/segment.go
  internal/storage/sql/common/util.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/namespaces_test.go
  internal/storage/sql/rule_test.go
  internal/storage/sql/segment_test.go
Labels: size/L

#1799 chore: add docker to devcontainer so can run tests
  .devcontainer/devcontainer.json
  .devcontainer/welcome-message.txt
  _tools/go.mod
  _tools/go.sum
  magefile.go
Labels: size/M

#1804 chore: add to codecov ignore
  codecov.yml
Labels: size/S

#1803 fix: context cancelled/deadline exceeded errors coming back internal
  internal/cmd/grpc.go
  internal/server/auth/middleware.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
Labels: size/M

#1809 Update import in the Go SDK README
  sdk/go/README.md
Labels: size/XS

#1800 test(integration): ensure Evaluation.Variant returns as expected
  build/testing/integration/api/api.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/default.yaml
  build/testing/integration/readonly/testdata/production.yaml
Labels: size/L

#1807 chore: fix deprecated archive replacement
  .goreleaser.yml
Labels: size/XS

#1798 feat: implement gRPC server for the Variant RPC method
  build/testing/integration/api/api.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/default.yaml
  build/testing/integration/readonly/testdata/production.yaml
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_store_mock.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/evaluator.go
  internal/server/evaluation/evaluator_mock.go
  internal/server/evaluation/evaluator_test.go
  internal/server/evaluation/server.go
  internal/server/evaluator.go
  internal/server/evaluator_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/server.go
  rpc/flipt/evaluation/evaluation.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.proto
  rpc/flipt/flipt.go
Labels: size/XXL
