Repository flipt-io/flipt, pull requests merged in 2023-11, with the labels that each got.

#2330 feat: Evaluation snapshot service
  go.work.sum
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/cmd/protoc-gen-go-flipt-sdk/main.go
  internal/ext/exporter.go
  internal/server/evaluation/data/server.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.pb.gw.go
  rpc/flipt/evaluation/evaluation.proto
  rpc/flipt/evaluation/evaluation_grpc.pb.go
  rpc/flipt/flipt.yaml
Labels: wip

#2357 feat: add boolean exported unsafe FFI function and couple other fixes
  client/engine/src/evaluator/mod.rs
  client/engine/src/lib.rs
  client/engine/src/models/transport/mod.rs
Labels: automerge

#2352 feat: supporting namespaced auth tokens
  build/generate/screenshots.go
  build/testing/integration.go
  build/testing/integration/api/api.go
  build/testing/integration/api/api_test.go
  build/testing/integration/api/authenticated.go
  build/testing/integration/integration.go
  build/testing/integration/readonly/readonly_test.go
  config/flipt.schema.cue
  config/flipt.schema.json
  config/local.yml
  internal/cmd/auth.go
  internal/cmd/grpc.go
  internal/server/auth/method/github/server.go
  internal/server/auth/method/github/server_test.go
  internal/server/auth/method/kubernetes/server.go
  internal/server/auth/method/kubernetes/server_internal_test.go
  internal/server/auth/method/oidc/server.go
  internal/server/auth/method/oidc/server_internal_test.go
  internal/server/auth/method/token/server.go
  internal/server/auth/method/token/server_test.go
  internal/server/auth/middleware/common/common.go
  internal/server/auth/middleware/grpc/middleware.go
  internal/server/auth/middleware/grpc/middleware_test.go
  internal/server/auth/middleware/http/middleware.go
  internal/server/auth/middleware/http/middleware_test.go
  internal/server/auth/middleware_test.go
  internal/server/auth/public/server.go
  internal/server/auth/server.go
  internal/server/auth/server_test.go
  internal/server/evaluation/server.go
  internal/server/evaluation/server_test.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/server.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/evaluation/evaluation.go
  rpc/flipt/flipt.proto
  rpc/flipt/scoped.go
  ui/screenshot/concepts/settings_tokens.js
  ui/screenshot/getting_started/create_constraint.js
  ui/screenshot/getting_started/create_flag.js
  ui/screenshot/getting_started/create_rule.js
  ui/screenshot/getting_started/create_segment.js
  ui/screenshot/getting_started/create_variant.js
  ui/src/app/tokens/Tokens.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/src/components/rollouts/forms/RolloutForm.tsx
  ui/src/components/tokens/TokenForm.tsx
  ui/src/components/tokens/TokenTable.tsx
  ui/src/types/auth/Token.ts
  ui/tests/tokens.spec.ts
Labels: needs docs

#2438 fix(ui/token): default namespaced token does not get created without …
  ui/src/components/tokens/TokenForm.tsx
Labels: automerge

#2439 fix(ui/token): show search input if it contains user's input
  ui/src/components/tokens/TokenTable.tsx
Labels: automerge

#2440 chore: rm Mastadon footer (sorry Mastadon); skip uffizzi workflow on …
  .github/workflows/uffizzi-preview.yml
  ui/src/components/Footer.tsx
Labels: automerge

#2443 feat: Added TLS options for git sources with self-signed certificates
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/grpc.go
  internal/config/storage.go
  internal/storage/fs/git/source.go
  internal/storage/fs/git/source_test.go
Labels: needs docs

#2464 fix(ui/console): monaco web workers don't work
  ui/src/components/console/ContextEditor.tsx
  ui/src/components/console/worker.ts
Labels: automerge

#2451 feat: Add pre-commit hook support
  .pre-commit-hooks.yaml
Labels: automerge

#2467 fix(ui/console): rework monaco editor
  ui/src/app/console/Console.tsx
  ui/src/components/console/ContextEditor.tsx
Labels: automerge
