Repository flipt-io/flipt, pull requests merged in 2023-02, with the labels that each got.

#1297 fix/feat: use joins instead of n+1/opening multiple connections
  internal/cmd/grpc.go
  internal/info/flipt.go
  internal/storage/sql/common/evaluation.go
  internal/storage/sql/common/flag.go
  internal/storage/sql/common/rule.go
  internal/storage/sql/common/segment.go
  internal/storage/sql/db.go
  internal/storage/sql/db_internal_test.go
Labels: size/XL

#1309 chore: release v1.18.1
  CHANGELOG.md
  version.txt
Labels: size/M

#1308 feat: add latest version url to info payload
  cmd/flipt/main.go
  internal/info/flipt.go
  internal/release/check.go
Labels: size/M

#1313 chore: add new log keys to config schemas
  config/flipt.schema.cue
  config/flipt.schema.json
Labels: size/M

#1314 fix: 500/ dont expose invalid base64 decode error for page token
  internal/server/flag.go
  internal/server/flag_test.go
  internal/server/rule.go
  internal/server/rule_test.go
  internal/server/segment.go
  internal/server/segment_test.go
Labels: size/M

#1315 chore: add otel logo to README
  README.md
  logos/opentelemetry.svg
Labels: size/XS

#1317 chore: add frame-ancestors directive to CSP header
  internal/cmd/http.go
Labels: size/XS

#1316 feat/proposal: Deprecate jaeger enabled
  DEPRECATIONS.md
  config/default.yml
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/grpc.go
  internal/config/cache.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/deprecations.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/deprecated/tracing_jaeger_enabled.yml
  internal/config/tracing.go
Labels: size/L

#1323 feat: Zipkin otel
  README.md
  config/flipt.schema.cue
  config/flipt.schema.json
  examples/images/zipkin.png
  examples/tracing/README.md
  examples/tracing/jaeger/README.md
  examples/tracing/jaeger/docker-compose.yml
  examples/tracing/zipkin/README.md
  examples/tracing/zipkin/docker-compose.yml
  go.mod
  go.sum
  internal/cmd/grpc.go
  internal/config/config_test.go
  internal/config/testdata/tracing/zipkin.yml
  internal/config/tracing.go
  internal/server/otel/noop_provider.go
Labels: size/L

#1325 Stackhawk
  .github/workflows/nightly.yml
  stackhawk.yml
Labels: size/M

#1324 feat: OTLP Exporter
  DEPRECATIONS.md
  README.md
  config/default.yml
  config/flipt.schema.cue
  config/flipt.schema.json
  examples/authentication/dex/docker-compose.yml
  examples/authentication/proxy/docker-compose.yml
  examples/cockroachdb/docker-compose.yml
  examples/images/opentelemetry.svg
  examples/mysql/docker-compose.yml
  examples/openfeature/docker-compose.yml
  examples/openfeature/main.go
  examples/postgres/docker-compose.yml
  examples/prometheus/docker-compose.yml
  examples/redis/docker-compose.yml
  examples/tracing/README.md
  examples/tracing/jaeger/docker-compose.yml
  examples/tracing/otlp/README.md
  examples/tracing/otlp/docker-compose.yml
  examples/tracing/otlp/otel-collector-config.yaml
  examples/tracing/zipkin/docker-compose.yml
  go.mod
  go.sum
  internal/cmd/grpc.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/deprecations.go
  internal/config/testdata/tracing/zipkin.yml
  internal/config/tracing.go
Labels: size/L

#1326 chore: bump multiple otel dependencies and fix API changes
  go.mod
  go.sum
  internal/metrics/metrics.go
  internal/server/cache/metrics.go
  internal/server/metrics/metrics.go
Labels: automerge, size/L

#1337 fix(cleanup): ensure all methods register their cleanup schedules
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/config/authentication.go
Labels: size/L

#1336 test(auth): ensure failed cookie auth attempt instructs user-agent to clear cookie
  internal/cmd/auth.go
  internal/server/auth/http.go
  internal/server/auth/http_test.go
  test/api.sh
Labels: automerge, size/L

#1338 chore: prepare for 1.18.2 release
  CHANGELOG.md
  DEPRECATIONS.md
  version.txt
Labels: size/S

#1339 chore: downcase log for cleanup skipped
  internal/cleanup/cleanup.go
Labels: automerge, size/XS

#1340 feat(config): add kubernetes authentication method configuration parameters
  internal/config/authentication.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/authentication/kubernetes.yml
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
Labels: auth, automerge, size/L

#1345 chore: switch to official redis client and redis-cache/v9
  go.mod
  go.sum
  internal/cmd/grpc.go
  internal/server/cache/redis/cache.go
  internal/server/cache/redis/cache_test.go
Labels: size/M

#1349 chore: fix dependencies after testcontainers-go bump
  go.mod
  go.sum
Labels: automerge, size/XS

#1341 feat(rpc/auth): define AuthenticationMethodKubernetesService proto
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/auth/auth_grpc.pb.go
  rpc/flipt/flipt.yaml
Labels: automerge, size/S

#1344 feat(auth/k8s): initial auth method service implementation
  internal/cmd/auth.go
  internal/config/authentication.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
  internal/server/auth/method/kubernetes/server.go
  internal/server/auth/method/kubernetes/server_internal_test.go
  internal/server/auth/method/kubernetes/server_test.go
  internal/server/auth/method/kubernetes/testing/grpc.go
  internal/server/auth/method/kubernetes/testing/http.go
  internal/server/auth/method/kubernetes/verify.go
Labels: size/XL

#1350 feat: enable ability to specify bootstrap token
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/auth.go
  internal/config/authentication.go
  internal/config/config_test.go
  internal/config/testdata/authentication/token_bootstrap_token.yml
  internal/config/testdata/authentication/token_negative_interval.yml
  internal/config/testdata/authentication/token_zero_grace_period.yml
  internal/storage/auth/auth.go
  internal/storage/auth/bootstrap.go
  internal/storage/auth/memory/store.go
  internal/storage/auth/sql/store.go
Labels: size/L

#1352 chore: update CHANGELOG for release 1.19
  CHANGELOG.md
Labels: size/XS

#1353 chore(cleanup): only log skip message when method enabled
  internal/cleanup/cleanup.go
Labels: size/XS

#1356 Nextjs Example
  README.md
  examples/authentication/proxy/Caddyfile
  examples/authentication/proxy/README.md
  examples/authentication/proxy/docker-compose.yml
  examples/images/nextjs-client-side.png
  examples/images/nextjs-server-side.png
  examples/images/nextjs.png
  examples/nextjs/Caddyfile
  examples/nextjs/Dockerfile
  examples/nextjs/README.md
  examples/nextjs/components/Greeting.tsx
  examples/nextjs/docker-compose.yml
  examples/nextjs/flipt.db
  examples/nextjs/hooks/flipt.tsx
  examples/nextjs/next-env.d.ts
  examples/nextjs/next.config.js
  examples/nextjs/package-lock.json
  examples/nextjs/package.json
  examples/nextjs/pages/_app.tsx
  examples/nextjs/pages/_document.tsx
  examples/nextjs/pages/api/hello.ts
  examples/nextjs/pages/index.tsx
  examples/nextjs/postcss.config.js
  examples/nextjs/public/favicon.ico
  examples/nextjs/styles/globals.css
  examples/nextjs/tailwind.config.js
  examples/nextjs/tsconfig.json
  examples/openfeature/docker-compose.yml
  examples/tracing/jaeger/docker-compose.yml
  examples/tracing/otlp/docker-compose.yml
  examples/tracing/zipkin/docker-compose.yml
Labels: size/L

#1358 chore: move database examples under common folder
  examples/database/README.md
  examples/database/cockroachdb/Dockerfile
  examples/database/cockroachdb/README.md
  examples/database/cockroachdb/docker-compose.yml
  examples/database/mysql/Dockerfile
  examples/database/mysql/README.md
  examples/database/mysql/docker-compose.yml
  examples/database/postgres/Dockerfile
  examples/database/postgres/README.md
  examples/database/postgres/docker-compose.yml
Labels: size/S

#1359 Grafana metrics example
  examples/images/grafana-dashboard.png
  examples/images/grafana.svg
  examples/metrics/README.md
  examples/metrics/docker-compose.yml
  examples/metrics/prometheus.yml
  examples/prometheus/docker-compose.yml
  examples/prometheus/prometheus.png
Labels: size/L

#1361 chore: Example cleanup
  examples/authentication/dex/docker-compose.yml
  examples/authentication/proxy/docker-compose.yml
  examples/basic/docker-compose.yml
  examples/database/cockroachdb/README.md
  examples/database/cockroachdb/docker-compose.yml
  examples/database/mysql/README.md
  examples/database/mysql/docker-compose.yml
  examples/database/postgres/README.md
  examples/database/postgres/docker-compose.yml
  examples/images/logos/cockroachdb.svg
  examples/images/logos/grafana.svg
  examples/images/logos/mysql.svg
  examples/images/logos/openfeature.svg
  examples/images/logos/opentelemetry.svg
  examples/images/logos/postgresql.svg
  examples/images/logos/prometheus.svg
  examples/images/logos/redis.svg
  examples/images/logos/sqlite.svg
  examples/metrics/README.md
  examples/metrics/docker-compose.yml
  examples/nextjs/docker-compose.yml
  examples/openfeature/README.md
  examples/openfeature/docker-compose.yml
  examples/redis/README.md
  examples/redis/docker-compose.yml
  examples/tracing/README.md
  examples/tracing/jaeger/docker-compose.yml
  examples/tracing/otlp/docker-compose.yml
  examples/tracing/zipkin/docker-compose.yml
Labels: size/L

#1367 Release/1.19
  CHANGELOG.md
  version.txt
Labels: size/S
