Repository flipt-io/flipt, pull requests merged in 2023-01, with the labels that each got.

#1250 feat(metadata): authenticate /meta endpoints
  cmd/flipt/main.go
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/server/metadata/server.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/flipt.yaml
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/meta/meta.pb.gw.go
  rpc/flipt/meta/meta.proto
  rpc/flipt/meta/meta_grpc.pb.go
  test/api.sh
Labels: size/L

#1251 chore: proto/buf updates
  rpc/flipt/buf.lock
Labels: size/XS

#1255 chore: use minted GITHUB_TOKEN for task setup to avoid ratelimits
  .github/workflows/integration-test.yml
  .github/workflows/nightly.yml
  .github/workflows/release-clients.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: size/M

#1254 chore: Release check refactor
  cmd/flipt/main.go
  go.mod
  internal/release/check.go
  internal/release/check_test.go
Labels: size/L

#1253 feat(http): support CSRF provention
  .gitleaksignore
  go.mod
  go.sum
  internal/cmd/http.go
  internal/config/authentication.go
  internal/config/config_test.go
  internal/config/testdata/advanced.yml
  test/api.sh
  test/config/test-with-auth.yml
  ui/src/services/api.js
  ui/src/store/index.js
Labels: size/L

#1260 fix(ui): support embedding nextjs static sites with dynamic pages
  internal/cmd/http.go
  internal/cmd/testdata/bar/[pid]/index.html
  internal/cmd/testdata/bar/baz/index.html
  internal/cmd/testdata/foo/index.html
  internal/cmd/testdata/index.html
  internal/cmd/ui.go
  internal/cmd/ui_test.go
Labels: size/L

#1269 chore: prep for v1.17 release
  .goreleaser.yml
  CHANGELOG.md
  DEPRECATIONS.md
  Taskfile.yml
  version.txt
Labels: size/M

#1270 chore: Post UI v2 updates
  .github/images/console.png
  .github/images/flags.png
  .github/workflows/release.yml
  README.md
  demo.gif
  ui/README.md
Labels: size/M

#1271 chore: try to fix post release workflows to trigger
  .github/workflows/post-release.yml
  .github/workflows/release-clients.yml
Labels: size/S

#1272 chore: rm branch from post release workflows
  .github/workflows/post-release.yml
  .github/workflows/release-clients.yml
Labels: size/XS

#1273 chore: switch from Task to Mage
  .github/workflows/integration-test.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .tool-versions
  Brewfile
  DEVELOPMENT.md
  Dockerfile
  README.md
  Taskfile.yml
  go.mod
  go.sum
  magefile.go
  script/bootstrap
  script/server
  script/test
Labels: size/XL

#1275 chore: update auth method metadata structure
  internal/config/authentication.go
  internal/server/auth/public/server.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
Labels: size/S

#1274 fix: auth/cookie fixes for OIDC login
  internal/config/authentication.go
  internal/config/config_test.go
  internal/config/testdata/authentication/session_domain_scheme_port.yml
  internal/server/auth/method/oidc/http.go
  internal/server/auth/method/oidc/server.go
  internal/server/auth/method/oidc/server_internal_test.go
Labels: size/L

#1277 fix(meta): remove `runtime.HttpBodyMarshaler` from gateway stack
  internal/cmd/http.go
  test/api.sh
Labels: automerge, size/S

#1278 chore: make UI dev easier
  .devcontainer/devcontainer.json
  DEVELOPMENT.md
  config/local.yml
  internal/cmd/http.go
  magefile.go
  ui/doc.go
  ui/embed.go
  ui/index.html
Labels: size/M

#1280 fix(csrf): dont attempt to create CSRF token when key is not defined
  internal/cmd/http.go
Labels: automerge, size/XS

#1279 feat: auth expire self / logout
  internal/cmd/auth.go
  internal/server/auth/http.go
  internal/server/auth/http_test.go
  internal/server/auth/method/oidc/http.go
  internal/server/auth/server.go
  internal/server/auth/server_test.go
  internal/storage/auth/auth.go
  internal/storage/auth/memory/store.go
  internal/storage/auth/sql/store.go
  internal/storage/auth/testing/testing.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/auth/auth_grpc.pb.go
  rpc/flipt/flipt.yaml
  test/api.sh
Labels: size/L

#1281 fix: mage bootstrap command
  magefile.go
Labels: size/S

#1282 chore: rm duplicate grpc shutdown log
  internal/cmd/grpc.go
Labels: size/XS

#1284 chore: move example images around
  examples/authentication/dex/README.md
  examples/cockroachdb/README.md
  examples/images/cockroachdb.svg
  examples/images/dex.png
  examples/images/jaeger-openfeature-otel.jpg
  examples/images/jaeger.jpg
  examples/images/mysql.svg
  examples/images/openfeature.svg
  examples/images/postgresql.svg
  examples/images/prometheus.svg
  examples/images/redis.svg
  examples/images/sqlite.svg
  examples/mysql/README.md
  examples/openfeature/README.md
  examples/postgres/README.md
  examples/prometheus/README.md
  examples/redis/README.md
  examples/tracing/README.md
  examples/tracing/jaeger.png
Labels: size/M

#1287 feat(github): trigger update helm charts on post release
  .github/workflows/post-release.yml
Labels: size/XS

#1283 chore: auth example refactor + dex
  examples/authentication/README.md
  examples/authentication/dex/README.md
  examples/authentication/dex/config.yaml
  examples/authentication/dex/dex-config.yaml
  examples/authentication/dex/docker-compose.yml
  examples/authentication/proxy/Caddyfile
  examples/authentication/proxy/README.md
  examples/authentication/proxy/docker-compose.yml
  examples/cockroachdb/README.md
  examples/images/cockroachdb.svg
  examples/images/dex.png
  examples/images/jaeger-openfeature-otel.jpg
  examples/images/jaeger.jpg
  examples/images/mysql.svg
  examples/images/openfeature.svg
  examples/images/postgresql.svg
  examples/images/prometheus.svg
  examples/images/redis.svg
  examples/images/sqlite.svg
  examples/mysql/README.md
  examples/openfeature/README.md
  examples/postgres/README.md
  examples/prometheus/README.md
  examples/redis/README.md
  examples/tracing/README.md
  examples/tracing/jaeger.png
Labels: size/L

#1290 chore: remove tag/push latest for now
  .github/workflows/release.yml
Labels: size/S

#1292 chore: add oidc logo/mention to README; fix misspellings
  README.md
  logos/openid.svg
Labels: size/S

#1294 chore: add public roadmap links/badge
  README.md
Labels: size/XS

#1293 feat: set csp and content-type-options headers
  internal/cmd/http.go
Labels: size/XS

#1296 fix: get linter running correctly locally
  .golangci.yml
Labels: size/S

#1295 feat(logging): support custom time, level and message keys
  cmd/flipt/main.go
  internal/config/config_test.go
  internal/config/log.go
  internal/config/testdata/advanced.yml
Labels: size/S

#1304 fix: disable csp headers in non-release mode for ui dev
  cmd/flipt/main.go
  internal/cmd/http.go
  internal/info/flipt.go
Labels: size/S

#1306 Otel improvements
  examples/tracing/docker-compose.yml
  internal/cmd/grpc.go
  internal/server/evaluator.go
  internal/server/flag.go
  internal/server/otel/attributes.go
  internal/server/otel/noop_exporter.go
Labels: size/M

#1305 chore: bump prom verison
  go.mod
  go.sum
Labels: size/XS

#1307 chore: add benchmark tests for list flags/segments
  .github/workflows/benchmark.yml
  internal/cleanup/cleanup_test.go
  internal/server/cache/redis/cache_test.go
  internal/storage/oplock/testing/testing.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/segment_test.go
  magefile.go
Labels: size/L
