Repository flipt-io/flipt, pull requests merged in 2023-03, with the labels that each got.

#1368 feat: (sqlite) support namespace at storage level, mostly for flags
  config/migrations/sqlite3/6_create_namespaces.down.sql
  config/migrations/sqlite3/6_create_namespaces.up.sql
  config/migrations/sqlite3/7_namespaces_migration.down.sql
  config/migrations/sqlite3/7_namespaces_migration.up.sql
  internal/ext/exporter.go
  internal/ext/exporter_test.go
  internal/server/evaluator.go
  internal/server/evaluator_test.go
  internal/server/flag.go
  internal/server/flag_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/support_test.go
  internal/server/support_test.go
  internal/storage/sql/common/flag.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/migrator.go
  internal/storage/sql/mysql/mysql.go
  internal/storage/sql/sqlite/sqlite.go
  internal/storage/storage.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/flipt.proto
Labels: size/XL

#1369 feat: Namespaces segments storage
  config/migrations/sqlite3/7_namespaces_migration_flags.down.sql
  config/migrations/sqlite3/7_namespaces_migration_flags.up.sql
  config/migrations/sqlite3/8_namespaces_migration_segments.down.sql
  config/migrations/sqlite3/8_namespaces_migration_segments.up.sql
  internal/ext/exporter.go
  internal/ext/exporter_test.go
  internal/server/middleware/grpc/support_test.go
  internal/server/segment.go
  internal/server/segment_test.go
  internal/server/support_test.go
  internal/storage/sql/common/flag.go
  internal/storage/sql/common/segment.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/migrator.go
  internal/storage/sql/segment_test.go
  internal/storage/sql/sqlite/sqlite.go
  internal/storage/storage.go
Labels: size/L

#1371 feat: (sqlite) add namespace support for rules storage
  internal/ext/exporter.go
  internal/ext/exporter_test.go
  internal/server/middleware/grpc/support_test.go
  internal/server/rule.go
  internal/server/rule_test.go
  internal/server/support_test.go
  internal/storage/sql/common/flag.go
  internal/storage/sql/common/rule.go
  internal/storage/sql/common/segment.go
  internal/storage/sql/flag_test.go
  internal/storage/sql/rule_test.go
  internal/storage/sql/segment_test.go
  internal/storage/storage.go
Labels: size/L

#1373 chore: add Prose logo to README
  README.md
  logos/users/prose.png
Labels: size/XS

#1386 Namespaces mysql
  config/migrations/mysql/4_create_namespaces.down.sql
  config/migrations/mysql/4_create_namespaces.up.sql
  config/migrations/mysql/5_namespaces_flags.down.sql
  config/migrations/mysql/5_namespaces_flags.up.sql
  config/migrations/mysql/6_namespaces_segments.down.sql
  config/migrations/mysql/6_namespaces_segments.up.sql
  config/migrations/mysql/7_namespaces_rules.down.sql
  config/migrations/mysql/7_namespaces_rules.up.sql
  config/migrations/sqlite3/7_namespaces_flags.down.sql
  config/migrations/sqlite3/7_namespaces_flags.up.sql
  config/migrations/sqlite3/8_namespaces_segments.down.sql
  config/migrations/sqlite3/8_namespaces_segments.up.sql
  internal/storage/sql/common/namespace.go
  internal/storage/sql/migrator.go
  internal/storage/sql/mysql/mysql.go
  internal/storage/sql/sqlite/sqlite.go
Labels: size/M

#1385 refactor(mod): create separate `errors` and `rpc/flipt` packages
  .gitleaks.toml
  errors/go.mod
  errors/go.sum
  go.mod
  go.work
  go.work.sum
  rpc/flipt/go.mod
  rpc/flipt/go.sum
Labels: size/XL

#1390 Namespaces cockroach
  config/migrations/cockroachdb/3_create_namespaces.down.sql
  config/migrations/cockroachdb/3_create_namespaces.up.sql
  config/migrations/cockroachdb/4_namespaces_flags.down.sql
  config/migrations/cockroachdb/4_namespaces_flags.up.sql
  config/migrations/cockroachdb/5_namespaces_segments.down.sql
  config/migrations/cockroachdb/5_namespaces_segments.up.sql
  config/migrations/cockroachdb/6_namespaces_rules.down.sql
  config/migrations/cockroachdb/6_namespaces_rules.up.sql
  internal/storage/sql/migrator.go
  internal/storage/sql/testing/testing.go
Labels: size/M

#1395 chore: update readme w better usecase verbiage
  README.md
Labels: size/S

#1399 fix: import for cockroach db
  cmd/flipt/export.go
  cmd/flipt/import.go
  go.work.sum
  internal/storage/sql/migrator.go
Labels: size/XS

#1397 fix: return better error messages for grpc-gateway errors
  internal/cmd/auth.go
  internal/cmd/http.go
  internal/gateway/gateway.go
  internal/server/auth/method/kubernetes/testing/http.go
  internal/server/auth/method/oidc/testing/http.go
  rpc/flipt/marshaller.go
  test/api.sh
Labels: automerge, size/M

#1396 chore: namespaces down migrations
  cmd/flipt/import.go
  config/migrations/cockroachdb/3_create_namespaces.down.sql
  config/migrations/cockroachdb/4_namespaces_flags.down.sql
  config/migrations/cockroachdb/4_namespaces_flags.up.sql
  config/migrations/cockroachdb/4_namespaces_relationships.down.sql
  config/migrations/cockroachdb/4_namespaces_relationships.up.sql
  config/migrations/cockroachdb/5_namespaces_segments.down.sql
  config/migrations/cockroachdb/5_namespaces_segments.up.sql
  config/migrations/cockroachdb/6_namespaces_rules.down.sql
  config/migrations/cockroachdb/6_namespaces_rules.up.sql
  config/migrations/mysql/5_namespaces_flags.down.sql
  config/migrations/mysql/5_namespaces_flags.up.sql
  config/migrations/mysql/5_namespaces_relationships.down.sql
  config/migrations/mysql/5_namespaces_relationships.up.sql
  config/migrations/mysql/6_namespaces_segments.down.sql
  config/migrations/mysql/6_namespaces_segments.up.sql
  config/migrations/mysql/7_namespaces_rules.down.sql
  config/migrations/mysql/7_namespaces_rules.up.sql
  config/migrations/postgres/1_variants_unique_per_flag.down.sql
  config/migrations/postgres/1_variants_unique_per_flag.up.sql
  config/migrations/postgres/6_create_namespaces.down.sql
  config/migrations/postgres/7_namespaces_flags.down.sql
  config/migrations/postgres/7_namespaces_flags.up.sql
  config/migrations/postgres/7_namespaces_relationships.down.sql
  config/migrations/postgres/7_namespaces_relationships.up.sql
  config/migrations/postgres/8_namespaces_segments.down.sql
  config/migrations/postgres/8_namespaces_segments.up.sql
  config/migrations/postgres/9_namespaces_rules.down.sql
  config/migrations/postgres/9_namespaces_rules.up.sql
  config/migrations/sqlite3/7_namespaces_flags.down.sql
  config/migrations/sqlite3/7_namespaces_flags.up.sql
  config/migrations/sqlite3/7_namespaces_relationships.down.sql
  config/migrations/sqlite3/7_namespaces_relationships.up.sql
  config/migrations/sqlite3/8_namespaces_segments.down.sql
  config/migrations/sqlite3/8_namespaces_segments.up.sql
  internal/storage/sql/migrator.go
Labels: size/XL

#1389 feat(sdk/go): thread client token on RPC calls when provided
  internal/cmd/protoc-gen-go-flipt-sdk/main.go
  sdk/go/auth.sdk.gen.go
  sdk/go/flipt.sdk.gen.go
  sdk/go/meta.sdk.gen.go
  sdk/go/sdk.gen.go
Labels: automerge, size/M

#1403 Release/1.19
  CHANGELOG.md
  version.txt
Labels: size/S

#1406 Namespaces: flags storage tests
  internal/storage/sql/db_test.go
  internal/storage/sql/flag_test.go
Labels: size/XL

#1408 Namespaces: segments storage tests
  internal/storage/sql/flag_test.go
  internal/storage/sql/segment_test.go
  magefile.go
Labels: size/L

#1421 Namespaces rpc
  internal/server/flag.go
  internal/server/namespace.go
  internal/server/namespace_test.go
  internal/server/rule.go
  internal/server/segment.go
  internal/storage/sql/common/namespace.go
  internal/storage/sql/namespaces_test.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
  rpc/flipt/flipt_grpc.pb.go
  sdk/go/flipt.sdk.gen.go
Labels: automerge, size/L

#1422 feat: check for protected or flags existing when deleting a namespace
  internal/server/namespace.go
  internal/server/namespace_test.go
Labels: size/L

#1423 test(integration): increase coverage to match existing suite
  hack/build/integration/integration.go
  hack/build/integration/integration_test.go
  internal/cmd/protoc-gen-go-flipt-sdk/http.go
  internal/cmd/protoc-gen-go-flipt-sdk/main.go
  sdk/go/auth.sdk.gen.go
  sdk/go/http/auth.sdk.gen.go
  sdk/go/http/meta.sdk.gen.go
Labels: automerge, size/XL

#1425 fix(github): use github go client to create tags
  .github/workflows/release-submodules.yml
  hack/build/go.mod
  hack/build/go.sum
  hack/build/release/release.go
Labels: size/L

#1427 chore: upgrade Go to 1.20
  .devcontainer/Dockerfile
  .github/workflows/benchmark.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .github/workflows/test.yml
  DEVELOPMENT.md
  Dockerfile
  _tools/go.mod
  errors/go.mod
  examples/basic/Dockerfile
  examples/basic/go.mod
  examples/openfeature/Dockerfile
  examples/openfeature/go.mod
  go.mod
  go.work
  go.work.sum
  hack/build/internal/flipt.go
  internal/config/authentication.go
  rpc/flipt/go.mod
  sdk/go/README.md
  sdk/go/go.mod
Labels: size/L

#1426 chore(sdk/go): rename everything from sdk to sdk/go
  README.md
  _tools/go.mod
  _tools/go.sum
  go.mod
  go.sum
  go.work.sum
  hack/build/go.mod
  hack/build/go.sum
  hack/build/integration/integration.go
  hack/build/integration/integration_test.go
  hack/build/internal/flipt.go
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/cmd/protoc-gen-go-flipt-sdk/main.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  sdk/go/README.md
  sdk/go/auth.sdk.gen.go
  sdk/go/doc.go
  sdk/go/flipt.sdk.gen.go
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/grpc/example_test.go
  sdk/go/grpc/grpc.sdk.gen.go
  sdk/go/http/auth.sdk.gen.go
  sdk/go/http/http.sdk.gen.go
  sdk/go/meta.sdk.gen.go
  sdk/go/sdk.gen.go
Labels: automerge, size/L

#1429 feat(sdk/go): add initial CHANGELOG
  sdk/go/CHANGELOG.md
  sdk/go/CHANGELOG.template.md
Labels: automerge, size/M

#1431 chore: release 1.19.3
  CHANGELOG.md
  _tools/go.mod
  _tools/go.sum
  build/Dockerfile
  go.mod
  go.sum
  hack/build/go.mod
  hack/build/go.sum
  version.txt
Labels: size/L

#1433 feat(sdk/go): prepare release v0.1.1
  sdk/go/CHANGELOG.md
  sdk/go/go.mod
Labels: automerge, size/S

#1436 feat(hack/build): add cases for namespace scoped integration tests
  hack/build/integration/integration.go
  hack/build/integration/integration_test.go
  hack/build/internal/test/integration.go
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/flipt.yaml
  sdk/go/flipt.sdk.gen.go
  sdk/go/http/flipt.sdk.gen.go
Labels: size/L

#1437 fix(rpc/flipt): move all openapi annotations into yaml file
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/meta/meta.proto
  rpc/flipt/openapiv2.yaml
Labels: size/XXL

#1438 fix(github): use event name workflow_run and conclusion
  .github/workflows/release-clients.yml
Labels: size/XS

#1445 fix: namespace segment REST API routes were not correct
  go.work.sum
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/flipt.yaml
  sdk/go/http/flipt.sdk.gen.go
Labels: size/L

#1446 fix(migrations/sqlite): reorder to ensure we copy all data before drop
  config/migrations/sqlite3/7_namespaces_relationships.up.sql
Labels: size/M

#1428 feat(github): dagger based integrations tests github workflow
  .github/workflows/integration-test.yml
  go.work.sum
  hack/build/Dockerfile
  hack/build/go.mod
  hack/build/go.sum
  hack/build/integration/integration.go
  hack/build/internal/test/integration.go
Labels: size/L

#1444 feat: add checks and tests for potential `namespace`d related failures
  hack/build/integration/integration.go
  internal/storage/sql/common/rule.go
  internal/storage/sql/evaluation_test.go
  internal/storage/sql/mysql/mysql.go
  internal/storage/sql/postgres/postgres.go
  internal/storage/sql/rule_test.go
  internal/storage/sql/sqlite/sqlite.go
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/flipt.yaml
  sdk/go/http/flipt.sdk.gen.go
Labels: size/L

#1448 chore: merge main into namespaces
  .github/workflows/integration-test.yml
  go.mod
  go.sum
  go.work.sum
  hack/build/Dockerfile
  hack/build/go.mod
  hack/build/go.sum
  hack/build/integration/integration.go
  hack/build/internal/test/integration.go
Labels: size/L

#1450 chore: add missing namespaces metrics
  internal/server/evaluator.go
  internal/server/metrics/metrics.go
Labels: size/S

#1449 chore: rm down migrations
  cmd/flipt/import.go
  codecov.yml
  config/migrations/cockroachdb/0_initial.down.sql
  config/migrations/cockroachdb/1_create_table_authentications.down.sql
  config/migrations/cockroachdb/2_create_table_operation_lock.down.sql
  config/migrations/cockroachdb/3_create_namespaces.down.sql
  config/migrations/cockroachdb/4_namespaces_relationships.down.sql
  config/migrations/mysql/0_initial.down.sql
  config/migrations/mysql/1_variants_attachment.down.sql
  config/migrations/mysql/2_create_table_authentications.down.sql
  config/migrations/mysql/3_create_table_operation_lock.down.sql
  config/migrations/mysql/4_create_namespaces.down.sql
  config/migrations/mysql/5_namespaces_relationships.down.sql
  config/migrations/postgres/0_initial.down.sql
  config/migrations/postgres/1_variants_unique_per_flag.down.sql
  config/migrations/postgres/2_segments_match_type.down.sql
  config/migrations/postgres/3_variants_attachment.down.sql
  config/migrations/postgres/4_create_table_authentications.down.sql
  config/migrations/postgres/5_create_table_operation_lock.down.sql
  config/migrations/postgres/6_create_namespaces.down.sql
  config/migrations/postgres/7_namespaces_relationships.down.sql
  config/migrations/sqlite3/0_initial.down.sql
  config/migrations/sqlite3/1_variants_unique_per_flag.down.sql
  config/migrations/sqlite3/2_segments_match_type.down.sql
  config/migrations/sqlite3/3_variants_attachment.down.sql
  config/migrations/sqlite3/4_create_table_authentications.down.sql
  config/migrations/sqlite3/5_create_table_operation_lock.down.sql
  config/migrations/sqlite3/6_create_namespaces.down.sql
  config/migrations/sqlite3/7_namespaces_relationships.down.sql
  internal/storage/sql/db.go
  internal/storage/sql/migrator.go
  internal/storage/sql/migrator_test.go
  internal/storage/sql/testing/testing.go
Labels: automerge, size/XL

#1453 fix: protojson to use DiscardUnknown option for backwards compatibility
  go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/http.go
  sdk/go/http/auth.sdk.gen.go
  sdk/go/http/flipt.sdk.gen.go
Labels: automerge, size/XS
