Repository flipt-io/flipt, pull requests merged in 2023-04, with the labels that each got.

#1457 chore: validation logic for namespace requests
  internal/ext/importer.go
  rpc/flipt/validation.go
  rpc/flipt/validation_test.go
Labels: size/L

#1456 fix(cmd/import): pass namespace key as name on create
  hack/build/testing/integration/readonly/readonly_test.go
Labels: size/S

#1460 chore: update changelog for future namespace release; add mage proto lint check
  .github/workflows/lint.yml
  CHANGELOG.md
Labels: size/M

#1465 feat(hack/build): release tooling
  .github/workflows/release-submodules.yml
  .github/workflows/release.yml
  cmd/flipt/import.go
  go.mod
  hack/build/go.mod
  hack/build/go.sum
  hack/build/magefile.go
  hack/build/release/changelog.go
  hack/build/release/release.go
  sdk/go/CHANGELOG.md
  sdk/go/go.mod
  version.txt
Labels: size/XL

#1468 chore: fix our devcontainer env to switch to using mage instead of task
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/devcontainer.yml
  .gitignore
  .vscode/flipt.code-workspace
Labels: size/M

#1470 chore: try to fix devcontainer build on actions
  .devcontainer/Dockerfile
Labels: size/XS

#1484 chore(sdk/go): upgrade rpc/flipt to v1.20.0
  go.mod
  sdk/go/CHANGELOG.md
  sdk/go/go.mod
Labels: automerge, size/XS

#1486 fix(github): install mage in release and prepend tag with v
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/M

#1485 chore: update changelog for 1.20 release
  CHANGELOG.md
Labels: size/XS

#1488 chore: move devcontainer image to be repo-scoped
  .github/workflows/devcontainer.yml
Labels: size/XS

#1458 feat: otel implementation for audit sinks
  go.mod
  internal/cmd/grpc.go
  internal/config/audit.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/audit/invalid_buffer_capacity.yml
  internal/config/testdata/audit/invalid_enable_without_file.yml
  internal/config/testdata/audit/invalid_flush_period.yml
  internal/server/audit/README.md
  internal/server/audit/audit.go
  internal/server/audit/audit_test.go
  internal/server/audit/logfile/logfile.go
  internal/server/auth/server_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/support_test.go
  internal/server/otel/noop_provider.go
Labels: automerge, size/XXL

#1494 chore(sdk/go): update docs examples to reference namespaces
  sdk/go/README.md
  sdk/go/defaults.go
  sdk/go/doc.go
  sdk/go/example_test.go
Labels: automerge, size/M

#1495 chore: update README with client libs
  README.md
Labels: size/S

#1497 chore: fix Dockerfile go mod download step
  Dockerfile
Labels: size/XS

#1493 feat(build): move hack/build into build
  .github/workflows/integration-test.yml
  .github/workflows/release.yml
  build/README.md
  build/go.mod
  build/go.sum
  build/internal/flipt.go
  build/internal/publish/publish.go
  build/internal/ui.go
  build/magefile.go
  build/release/changelog.go
  build/release/release.go
  build/testing/integration.go
  build/testing/integration/api/api.go
  build/testing/integration/api/api_test.go
  build/testing/integration/api/authenticated.go
  build/testing/integration/integration.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/readonly/testdata/seed.yaml
  build/testing/test.go
  go.work
Labels: automerge, size/M

#1496 chore: add example for audit logging to file in docker
  examples/audit/README.md
  examples/audit/docker-compose.yml
Labels: size/M

#1509 chore: dont ignore examples repo in CI
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
Labels: size/XS

#1510 chore: fix stringer error
  internal/server/middleware/grpc/support_test.go
Labels: automerge, size/XS

#1498 chore: audit author -> actor
  .github/workflows/lint.yml
  internal/server/audit/audit.go
  internal/server/audit/audit_test.go
  internal/server/auth/middleware.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/support_test.go
Labels: size/L

#1526 feat(build): mage test:ui and github action step
  .github/workflows/integration-test.yml
  .gitignore
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  build/internal/ui.go
  build/magefile.go
  build/testing/integration.go
  build/testing/ui.go
  go.mod
  go.sum
  go.work
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  ui/vite.config.ts
Labels: automerge, size/L

#1528 feat: add error highlighting in console
  ui/src/app/console/Console.tsx
Labels: size/S

#1527 chore: Telemetry updates
  cmd/flipt/main.go
  internal/config/authentication.go
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
  internal/telemetry/testdata/telemetry_v1.json
Labels: size/L

#1529 feat: add token creation and delete authentications for audit events
  internal/cmd/auth.go
  internal/cmd/grpc.go
  internal/server/audit/audit.go
  internal/server/auth/server.go
  internal/server/auth/server_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/support_test.go
Labels: automerge, size/L

#1545 fix(grpc/middleware): set timestamp on each batch evaluate response
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
Labels: automerge, size/XS

#1546 chore: prepare the 1.20.1 release
  .github/workflows/release.yml
  CHANGELOG.md
Labels: size/XS

#1547 Release/1.19
  CHANGELOG.md
  go.work.sum
Labels: automerge, size/XS

#1549 chore: cleanup and remove print statements
  internal/server/auth/server.go
  internal/server/auth/server_test.go
Labels: automerge, size/XS

#1551 chore: add audit configuration to json schema and cue file
  config/flipt.schema.cue
  config/flipt.schema.json
Labels: automerge, size/M

#1552 feat: make changes to audit event structure
  internal/server/audit/audit.go
  internal/server/audit/audit_test.go
  internal/server/auth/server.go
  internal/server/auth/server_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
Labels: automerge, size/L

#1550 fix(cmd/flipt): restore console logger defaults on fatal
  cmd/flipt/main.go
  test/cli.bats
Labels: automerge, size/M
