Repository flipt-io/flipt, pull requests merged in 2024-06, with the labels that each got.

#3145 add docstrings to functions
  build/main.go
Labels: automerge

#3113 feat: support writing audit events to stdout for log
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/grpc.go
  internal/config/audit.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/log.go
  internal/config/testdata/audit/enable_without_file.yml
  internal/server/audit/audit.go
  internal/server/audit/log/log.go
  internal/server/audit/log/log_test.go
  internal/server/audit/logfile/logfile.go
  internal/server/audit/logfile/logfile_test.go
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
Labels: needs docs

#3150 refactor(build): remove namespace from IT matrix and move into harness
  build/testing/integration.go
  build/testing/integration/api/api.go
  build/testing/integration/api/authenticated.go
  build/testing/integration/integration.go
  build/testing/integration/readonly/readonly_test.go
Labels: automerge

#3135 fix(auth): allow authorization for Github and OIDC behind the reverse proxy
  examples/proxy/README.md
  examples/proxy/dex.config.yml
  examples/proxy/docker-compose.yml
  examples/proxy/flipt.config.yml
  examples/proxy/hosts.txt
  examples/proxy/nginx.conf
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/cmd/authn.go
  internal/cmd/http.go
  internal/config/authentication.go
  internal/config/authentication_test.go
  internal/server/authn/method/http.go
  internal/server/authn/method/http_test.go
  internal/server/authn/method/oidc/testing/http.go
  internal/server/authn/public/server.go
  internal/server/authn/public/server_test.go
  ui/src/app/auth/Login.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/types/auth/Github.ts
  ui/src/types/auth/JWT.ts
  ui/src/types/auth/OIDC.ts
Labels: needs docs

#3151 fix(audit): preserve audit log scheme
  internal/server/audit/events.go
  internal/server/audit/events_test.go
  internal/server/audit/log/log.go
  internal/server/audit/log/log_test.go
Labels: automerge

#3153 chore: create docs issue for needs docs label
  .github/workflows/label.yml
Labels: automerge

#3156 chore: add hybrid cloud banner to readme
  .github/images/flipt-cloud.svg
  README.md
Labels: automerge

#3155 feat: Audit failed authz attempts
  .gitignore
  errors/errors.go
  internal/cmd/grpc.go
  internal/server/analytics/sink.go
  internal/server/audit/checker.go
  internal/server/audit/events.go
  internal/server/audit/events_test.go
  internal/server/audit/log/log_test.go
  internal/server/authz/middleware/grpc/middleware.go
  internal/server/authz/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  rpc/flipt/analytics/analytics_grpc.pb.go
  rpc/flipt/auth/auth_grpc.pb.go
  rpc/flipt/evaluation/evaluation_grpc.pb.go
  rpc/flipt/flipt_grpc.pb.go
  rpc/flipt/meta/meta_grpc.pb.go
  rpc/flipt/request.go
Labels: automerge

#3157 chore: refactor reverse proxy examples a bit
  examples/authentication/proxy/README.md
  examples/authentication/proxy/basic/Caddyfile
  examples/authentication/proxy/basic/README.md
  examples/authentication/proxy/basic/docker-compose.yml
  examples/authentication/proxy/oidc/README.md
  examples/authentication/proxy/oidc/dex.config.yml
  examples/authentication/proxy/oidc/docker-compose.yml
  examples/authentication/proxy/oidc/features.yml
  examples/authentication/proxy/oidc/flipt.config.yml
  examples/authentication/proxy/oidc/hosts.txt
  examples/authentication/proxy/oidc/nginx.conf
  examples/proxy/README.md
Labels: automerge

#3164 chore: refactor cache to rm from middleware and use storage layer
  build/internal/cmd/loadtest/main.go
  build/testing/integration/api/api.go
  go.work.sum
  internal/cmd/grpc.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/support_test.go
  internal/storage/cache/cache.go
  internal/storage/cache/cache_test.go
  internal/storage/cache/support_test.go
Labels: automerge

#3163 feat(build/testing): add authz specific integration tests
  .github/workflows/integration-test.yml
  build/testing/integration.go
  build/testing/integration/api/api.go
  build/testing/integration/authn/auth.go
  build/testing/integration/authz/auth.go
  build/testing/integration/authz/auth_test.go
  build/testing/integration/integration.go
  build/testing/integration/readonly/readonly_test.go
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/authorization/authentication_not_session_enabled.yml
  internal/server/authn/method/token/server.go
  internal/server/authn/method/token/server_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
  internal/storage/authn/bootstrap.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/auth/auth.proto
  rpc/flipt/request.go
Labels: automerge, needs docs

#3154 feat: allow to copy evaluate command in a CLI format
  ui/src/app/console/Console.tsx
  ui/src/components/forms/Dropdown.tsx
  ui/src/types/Cli.ts
  ui/src/utils/helpers.ts
Labels: automerge

#3169 chore: fix layout of copy evaluate button
  go.work.sum
  ui/src/app/console/Console.tsx
  ui/src/components/forms/Dropdown.tsx
  ui/src/components/forms/buttons/Button.tsx
Labels: automerge

#3149 fix(ui): prevent reload after logout
  ui/package-lock.json
  ui/package.json
  ui/src/components/Header.tsx
  ui/src/components/SessionProvider.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/data/api.test.ts
  ui/src/data/api.ts
  ui/src/data/hooks/storage.ts
  ui/src/data/user.ts
  ui/src/types/auth/Session.ts
  ui/src/types/auth/User.ts
Labels: automerge

#3170 chore: dont log grpc healthcheck
  internal/cmd/grpc.go
Labels: automerge

#3172 chore(deps)!: dump otel semconv to v1.25.0
  go.mod
  go.sum
  go.work.sum
  internal/metrics/metrics.go
  internal/server/otel/attributes.go
  internal/storage/sql/db.go
  internal/tracing/tracing.go
  internal/tracing/tracing_test.go
Labels: automerge

#3176 chore: Dagger cloud
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/proto.yml
  .github/workflows/release-tag-latest.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .github/workflows/test.yml
  go.work.sum
Labels: automerge

#3175 chore: Switch to jitsu
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .goreleaser.darwin.yml
  .goreleaser.linux.yml
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  cmd/flipt/main.go
  core/go.mod
  core/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
Labels: automerge

#3194 feat(authz): add opa bundle support
  .github/workflows/integration-test.yml
  .gitignore
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  build/testing/integration.go
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/cmd/grpc.go
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/config/authorization.go
  internal/config/config_test.go
  internal/config/storage.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/authorization/all_authentication_methods_enabled.yml
  internal/server/authn/method/github/server.go
  internal/server/authn/method/github/server_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
  internal/server/authn/server.go
  internal/server/authn/server_test.go
  internal/server/authz/authz.go
  internal/server/authz/engine/bundle/engine.go
  internal/server/authz/engine/bundle/engine_test.go
  internal/server/authz/engine/rego/engine.go
  internal/server/authz/engine/rego/engine_test.go
  internal/server/authz/engine/rego/source/filesystem/filesystem.go
  internal/server/authz/engine/rego/source/source.go
  internal/server/authz/engine/testdata/rbac.json
  internal/server/authz/engine/testdata/rbac.rego
  internal/server/authz/middleware/grpc/middleware.go
  internal/server/authz/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/middleware_test.go
  sdk/go/go.sum
  ui/src/app/Onboarding.tsx
  ui/src/app/flags/rollouts/Rollouts.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/Nav.tsx
  ui/src/components/forms/buttons/TextButton.tsx
  ui/src/components/rollouts/Rollout.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/data/api.ts
Labels: needs docs

#3203 feat: Rbac cloud
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/cmd/grpc.go
  internal/config/audit.go
  internal/config/authorization.go
  internal/config/config_test.go
  internal/config/experimental.go
  internal/server/audit/retryable_client.go
  internal/server/audit/retryable_client_test.go
  internal/server/audit/template/executer.go
  internal/server/audit/template/executer_test.go
  internal/server/audit/webhook/client.go
  internal/server/audit/webhook/client_test.go
  internal/server/audit/webhook/webhook.go
  internal/server/audit/webhook/webhook_test.go
  internal/server/authn/method/github/server.go
  internal/server/authn/method/github/server_test.go
  internal/server/authn/method/metadata.go
  internal/server/authn/method/oidc/server.go
  internal/server/authn/method/oidc/server_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/server.go
  internal/server/authz/engine/bundle/engine.go
  internal/server/authz/engine/rego/engine.go
  internal/server/authz/engine/rego/engine_test.go
  internal/server/authz/engine/rego/source/cloud/cloud.go
  internal/server/authz/engine/rego/source/cloud/cloud_test.go
  internal/server/authz/engine/rego/source/filesystem/filesystem.go
  internal/server/authz/engine/rego/source/source.go
  internal/telemetry/telemetry_test.go
Labels: automerge, needs docs

#3217 chore: Dont expose object store config json
  go.work.sum
  internal/config/storage.go
Labels: automerge

#3220 chore: add back build/Dockerfile for release
  .goreleaser.yml
  build/Dockerfile
Labels: automerge
