Repository flipt-io/flipt, pull requests merged in 2024-04, with the labels that each got.

#2937 fix(ui): evaluation console provides the warning for user about context values
  ui/package-lock.json
  ui/package.json
  ui/src/components/console/ContextEditor.tsx
  ui/src/components/console/lint.ts
Labels: automerge

#2936 feat(cmd): allow passing a working directory for flipt validate command
  cmd/flipt/validate.go
Labels: automerge

#2939 feat(fs/git): add support for a directory scope
  config/flipt.schema.cue
  config/flipt.schema.json
  go.work.sum
  internal/config/config_test.go
  internal/config/storage.go
  internal/config/testdata/storage/git_provided_with_directory.yml
  internal/storage/fs/git/store.go
  internal/storage/fs/git/store_test.go
  internal/storage/fs/git/testdata/subdir/.flipt.yml
  internal/storage/fs/git/testdata/subdir/alternative.yml
  internal/storage/fs/store/store.go
Labels: needs docs

#2953 fix(cache): accept a username in redis configuration
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/grpc.go
  internal/config/cache.go
  internal/config/config_test.go
  internal/config/testdata/cache/redis-username.yml
Labels: automerge

#2951 Add entityId to clickhouse analytics
  config/migrations/clickhouse/3_alter_add_entity_id.up.sql
  internal/server/analytics/clickhouse/mutation.go
  internal/server/analytics/sink.go
  internal/server/middleware/grpc/middleware.go
  internal/storage/sql/migrator.go
Labels: automerge

#2983 feat(config): support remote blob storage for service configuration
  build/testing/cli.go
  cmd/flipt/main.go
  internal/config/config.go
  internal/config/config_test.go
  internal/storage/fs/object/mux.go
  internal/storage/fs/object/mux_test.go
  internal/storage/fs/object/store.go
  internal/storage/fs/object/store_test.go
  internal/storage/fs/store/store.go
Labels: automerge, needs docs

#2984 feat: improve open telemetry tracing instrumentation
  config/flipt.schema.cue
  config/flipt.schema.json
  examples/openfeature/main.go
  go.mod
  go.sum
  internal/cmd/grpc.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/tracing/otlp.yml
  internal/config/testdata/tracing/wrong_propagator.yml
  internal/config/testdata/tracing/wrong_sampling_ratio.yml
  internal/config/tracing.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluator.go
  internal/server/otel/attributes.go
  internal/storage/sql/db.go
  internal/tracing/tracing.go
  internal/tracing/tracing_test.go
Labels: automerge, needs docs

#2995 feat(authn): allow validation of jwt subject claim
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cmd/authn.go
  internal/config/authentication.go
  internal/server/authn/middleware/grpc/middleware_test.go
Labels: needs docs

#2996 refactor(storage): move from lib/pq to pgx
  codecov.yml
  go.mod
  go.sum
  go.work.sum
  internal/storage/sql/adapted_driver.go
  internal/storage/sql/adapted_driver_test.go
  internal/storage/sql/db.go
  internal/storage/sql/db_internal_test.go
  internal/storage/sql/errors.go
  internal/storage/sql/errors_test.go
  internal/storage/sql/migrator.go
  internal/storage/sql/mock_pg_driver.go
  internal/storage/sql/postgres/postgres.go
Labels: automerge

#3021 feat: Oltp metrics exporter
  build/testing/integration/api/api.go
  build/testing/integration/integration.go
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/cmd/grpc.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/metrics.go
  internal/config/testdata/marshal/yaml/default.yml
  internal/config/testdata/metrics/disabled.yml
  internal/config/testdata/metrics/otlp.yml
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  internal/tracing/tracing_test.go
Labels: automerge, needs docs

#3022 Otlp http
  internal/metrics/metrics.go
  internal/tracing/tracing.go
  internal/tracing/tracing_test.go
Labels: automerge
