Repository flipt-io/flipt, pull requests merged in 2024-05, with the labels that each got.

#3040 Improve otlp metrics
  go.mod
  go.sum
  internal/cmd/grpc.go
  internal/metrics/metrics.go
Labels: automerge

#3036 chore: Release/1.41.1
  CHANGELOG.md
Labels: automerge

#3057 chore: bump to use go 1.22
  Dockerfile
  Dockerfile.dev
  _tools/go.mod
  build/go.mod
  build/internal/flipt.go
  core/go.mod
  errors/go.mod
  go.mod
  go.work
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/meta/meta.pb.go
  sdk/go/go.mod
Labels: automerge

#3044 fix(storage): make OCI reauthentication with AWS ECR
  go.mod
  go.sum
  go.work.sum
  internal/oci/ecr/credentials_store.go
  internal/oci/ecr/credentials_store_test.go
  internal/oci/ecr/ecr.go
  internal/oci/ecr/ecr_test.go
  internal/oci/ecr/mock_Client_test.go
  internal/oci/ecr/mock_PrivateClient_test.go
  internal/oci/ecr/mock_PublicClient_test.go
  internal/oci/ecr/mock_client.go
  internal/oci/file.go
  internal/oci/file_test.go
  internal/oci/mock_credentialFunc.go
  internal/oci/options.go
Labels: automerge

#3075 chore(refactor): remove unneeded goroutines in cloud login
  cmd/flipt/cloud.go
  go.work.sum
Labels: automerge

#3077 feat: add banner about cloud offering
  ui/src/app/Layout.tsx
  ui/src/app/Onboarding.tsx
  ui/src/app/events/eventSlice.ts
  ui/src/components/Banner.tsx
  ui/src/store.ts
  ui/tests/onboarding.spec.ts
Labels: automerge

#3081 chore: fix goreleaser deprecations
  .goreleaser.nightly.yml
  .goreleaser.yml
Labels: automerge

#3082 feat: logout redirect to cloud issuer
  cmd/flipt/cloud.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
  ui/src/components/Header.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/types/auth/Github.ts
  ui/src/types/auth/JWT.ts
  ui/src/types/auth/OIDC.ts
Labels: automerge

#3084 fix: nightly and snapshot builds (mage)
  .github/workflows/nightly.yml
  .github/workflows/snapshot.yml
Labels: automerge

#3102 feat(fs/git): add support for cloning target repository to the local filesystem
  internal/config/config_test.go
  internal/config/storage.go
  internal/config/testdata/storage/git_provided_with_backend_type.yml
  internal/storage/fs/git/store.go
  internal/storage/fs/git/store_test.go
  internal/storage/fs/store/store.go
Labels: needs docs

#3107 feat(cache/redis): support ca certificate and insecure tls options
  .github/workflows/integration-test.yml
  build/testing/integration.go
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/cache/redis/client.go
  internal/cache/redis/client_test.go
  internal/cmd/grpc.go
  internal/config/cache.go
  internal/config/config_test.go
  internal/config/testdata/cache/redis-ca-bytes.yml
  internal/config/testdata/cache/redis-ca-invalid.yml
  internal/config/testdata/cache/redis-ca-path.yml
  internal/config/testdata/cache/redis-tls-insecure.yml
Labels: automerge, needs docs

#3109 fix: write response for cloud login before server shutdown
  go.work.sum
  internal/cmd/cloud/local_server.go
Labels: automerge

#3111 fix: prevent redis shutdown
  internal/cmd/grpc.go
Labels: automerge

#3129 fix: issues with cloud config for cloud serve
  cmd/flipt/cloud.go
  go.mod
  go.sum
  go.work.sum
  internal/config/server.go
Labels: automerge

#3130 chore: prompt for login if no token
  cmd/flipt/cloud.go
Labels: automerge

#3138 chore(refactor): rename instance to gateway for flipt cloud
  cmd/flipt/cloud.go
  cmd/flipt/main.go
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/config/cloud.go
Labels: automerge

#3128 feat(ui): allow change top bar theme color
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/config/config_test.go
  internal/config/testdata/ui/topbar_color.yml
  internal/config/testdata/ui/topbar_invalid_color.yml
  internal/config/ui.go
  ui/src/App.tsx
  ui/src/app/meta/metaSlice.ts
  ui/src/components/Header.tsx
  ui/src/components/Sidebar.tsx
  ui/src/types/Meta.ts
Labels: automerge, needs docs
