Repository flipt-io/flipt, pull requests merged in 2024-11, with the labels that each got.

#3578 chore: try remove dagger cloud to see if it makes builds noticeably slower
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
Labels: automerge

#3591 fix(ofrep): forward x-flipt-namespace http header from grpc-gateway to the ofrep service
  internal/cmd/http.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
Labels: automerge

#3592 fix(ui): remove unnecessary scrolls for quick edit forms
  ui/src/app/flags/rules/Rules.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx
  ui/src/components/rules/forms/QuickEditRuleForm.tsx
Labels: automerge

#3595 fix: update attachment messaging and size to allow 1mb
  rpc/flipt/validation.go
Labels: automerge

#3597 fix: devcontainer update go version to 1.23
  .devcontainer/Dockerfile
Labels: automerge

#3598 chore: pin goreleaser to 2.3.x
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  go.work.sum
Labels: automerge

#3601 fix(ui): use dark scheme for browser built-in inputs/scrolls in dark mode
  ui/src/assets/colors/dark.css
Labels: automerge

#3619 feat(analytics): use Prometheus as source for analytics to display chart
  config/flipt.schema.cue
  config/flipt.schema.json
  examples/analytics/prometheus/docker-compose.yml
  examples/analytics/prometheus/prometheus.yml
  go.mod
  go.sum
  go.work.sum
  internal/cmd/grpc.go
  internal/config/analytics.go
  internal/config/analytics_test.go
  internal/server/analytics/analytics.go
  internal/server/analytics/analytics_test.go
  internal/server/analytics/clickhouse/client.go
  internal/server/analytics/clickhouse/client_test.go
  internal/server/analytics/mock_Client_test.go
  internal/server/analytics/prometheus/client.go
  internal/server/analytics/prometheus/client_test.go
  internal/server/analytics/prometheus/mock_prometheusClient_test.go
  internal/server/analytics/server.go
  internal/server/analytics/server_test.go
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/app/meta/metaSlice.ts
  ui/src/components/graphs/index.tsx
Labels: needs docs

#3633 chore(deps): go work sync
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  core/go.mod
  core/go.sum
  go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  sdk/go/go.mod
  sdk/go/go.sum
Labels: automerge

#3653 chore: prep for 1.52 release
  CHANGELOG.md
  go.work.sum
Labels: automerge

#3661 chore: Release/1.52.1
  CHANGELOG.md
Labels: automerge

#3654 FLI-1258: pass org and teams to metadata
  internal/server/authn/method/github/server.go
  internal/server/authn/method/github/server_test.go
Labels: automerge, needs docs

#3665 chore: slight refactor of github/auth server
  internal/server/authn/method/github/server.go
Labels: automerge
