Repository flipt-io/flipt, pull requests merged in 2025-10, with the labels that each got.

#4769 refactor(otel): align event and attribute names with OTEL spec
  internal/server/analytics/sink.go
  internal/server/analytics/sink_test.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/ofrep_bridge.go
  internal/server/tracing/attributes.go
  internal/server/tracing/attributes_test.go
Labels: size:L

#4813 chore: reduce how often contributor workflow runs
  .github/workflows/contributors.yml
Labels: size:XS

#4817 fix(build): update Dagger build to work without go.work files
  build/internal/flipt.go
Labels: size:M

#4818 refactor(build): use static go.work.container file instead of dynamic generation
  .github/workflows/integration-test.yml
  build/go.work.container
  build/internal/flipt.go
  build/main.go
Labels: size:M

#4815 chore: bump goreleaser to latest version on v2
  .github/workflows/release.yml
Labels: size:XS

#4816 fix: uts after removing go.work*
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  build/internal/flipt.go
  build/testing/migration.go
  core/go.mod
  core/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
Labels: size:L

#4814 chore: bump goreleaser to latest version in actions
  .github/workflows/release.yml
Labels: size:XS

#4812 chore: update changelog for 1.61.0 release
  .gitignore
  CHANGELOG.md
  go.work
  go.work.sum
Labels: size:S

#4775 refactor(authn/method): improve code style and error handling in util.go
  internal/server/authn/method/util.go
  internal/server/authn/method/util_test.go
Labels: automerge, size:M

#4847 fix(proto): generate openapi for v2 api with gnostic
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  magefile.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/core/core.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/options/options.pb.go
  rpc/v2/analytics/analytics.pb.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/environments_grpc.pb.go
  rpc/v2/environments/openapi.yaml
  rpc/v2/evaluation/evaluation.pb.go
Labels: size:XXL, v2

#4848 Add `Metadata` field to `ListFlags` API response
  internal/server/flag.go
  internal/server/flag_test.go
Labels: size:M

#4866 refactor(github): use go-github/v75
  devenv.lock
  go.mod
  go.sum
  internal/coss/storage/environments/git/github/github.go
  internal/coss/storage/environments/git/github/github_mock.go
  internal/coss/storage/environments/git/github/github_test.go
  internal/coss/storage/environments/git/gitlab/gitlab_mock.go
  internal/release/check.go
  internal/release/check_test.go
  internal/server/analytics/prometheus/prometheus_mock.go
Labels: automerge, size:L, v2

#4857 fix: ensure compatibility with SDKs and default environment
  internal/server/environments/storage.go
  internal/server/environments/storage_test.go
Labels: automerge, size:L, v2
