Repository flipt-io/flipt, pull requests merged in 2025-02, with the labels that each got.

#3860 chore: Add k6 Loadtest
  build/internal/cmd/loadtest/main.go
  build/load/README.md
  build/load/import.yaml
  build/load/loadtest.js
  go.work.sum
Labels: size:L

#3871 chore: Inproc
  cmd/flipt/main.go
  go.mod
  go.sum
  go.work.sum
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/server/evaluation/data/server.go
  internal/storage/environments/environments.go
  internal/storage/git/repository.go
Labels: size:L

#3872 fix(tests/config): get test suite back into passing state
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/storage.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/authentication/token_bootstrap_token.yml
  internal/config/testdata/authorization/all_authentication_methods_enabled.yml
  internal/config/testdata/storage/git_basic_auth_invalid.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_missing_password.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_private_key_both.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_private_key_missing.yml
  internal/config/testdata/storage/git_ssh_auth_valid_with_path.yml
Labels: size:L

#3874 fix(tests/middleware): ensure eval interceptor noop tests valid rpc
  internal/server/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/support_test.go
Labels: automerge, size:S

#3877 fix(storage/fs): various fixes and base test cases
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  internal/storage/fs/testdata/empty/features.yml
  internal/storage/fs/testdata/production/features.yaml
Labels: size:XL

#3875 feat: V2 UI (flag list + namespace list)
  config/local.yml
  internal/cmd/http.go
  internal/storage/git/filesystem.go
  ui/src/App.tsx
  ui/src/app/Layout.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/environments/environmentsApi.ts
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/Flags.tsx
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/app/flags/flagsApi.ts
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/meta/metaSlice.ts
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/namespaces/namespacesApi.ts
  ui/src/app/refs/refsSlice.ts
  ui/src/app/segments/Segment.tsx
  ui/src/app/segments/Segments.tsx
  ui/src/components/Button.tsx
  ui/src/components/Header.tsx
  ui/src/components/Nav.tsx
  ui/src/components/SessionProvider.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/forms/FlagForm.tsx
  ui/src/components/forms/SegmentsPicker.tsx
  ui/src/components/header/ReadOnly.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/panels/CopyToNamespacePanel.tsx
  ui/src/components/rollouts/Rollout.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/rollouts/SortableRollout.tsx
  ui/src/components/rollouts/forms/EditRolloutForm.tsx
  ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx
  ui/src/components/rollouts/forms/RolloutForm.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/components/rules/SortableRule.tsx
  ui/src/components/rules/forms/QuickEditRuleForm.tsx
  ui/src/components/rules/forms/RuleForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/tokens/TokenForm.tsx
  ui/src/components/variants/Variants.tsx
  ui/src/components/variants/forms/VariantForm.tsx
  ui/src/data/api.ts
  ui/src/store.ts
  ui/src/types/Environment.ts
  ui/src/types/Flag.ts
  ui/src/types/Meta.ts
  ui/src/types/Namespace.ts
  ui/vite.config.ts
Labels: size:XL, v2

#3878 test(server/evaluation): fixup server evaluation test suits to support envs
  .mockery.yaml
  internal/common/store_mock.go
  internal/server/environments/mock_environment.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/mock_environmentstore.go
  internal/server/evaluation/ofrep_bridge_test.go
  internal/storage/mock_readonlystore.go
Labels: size:XXL

#3881 chore: V2 UI flags
  internal/server/metadata/server.go
  internal/storage/environments/fs/flipt/flags.go
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/core/core.pb.go
  rpc/flipt/core/core.proto
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.yaml
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/meta/meta.pb.gw.go
  rpc/flipt/meta/meta.proto
  rpc/flipt/meta/meta_grpc.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/options/options.pb.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.yaml
  sdk/go/http/meta.sdk.gen.go
  sdk/go/meta.sdk.gen.go
  ui/src/App.tsx
  ui/src/app/flags/ConditionalFlagRouter.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/NewFlag.tsx
  ui/src/app/flags/flagsApi.ts
  ui/src/components/EmptyState.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/FlagFormContext.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/MetadataForm.tsx
  ui/src/components/flags/MetadataFormErrorBoundary.tsx
  ui/src/components/flags/forms/FlagForm.tsx
  ui/src/components/forms/JSONTextArea.tsx
  ui/src/components/variants/VariantForm.tsx
  ui/src/components/variants/Variants.tsx
  ui/src/types/Distribution.ts
  ui/src/types/Flag.ts
  ui/src/types/Resource.ts
  ui/src/types/Rule.ts
  ui/src/types/Variant.ts
  ui/src/utils/helpers.ts
Labels: size:XXL

#3879 fix(server/ofrep): use core instead of flipt package types
  internal/server/ofrep/evaluation.go
  internal/server/ofrep/server.go
  internal/storage/fs/local/store.go
  internal/storage/fs/local/store_test.go
Labels: size:L, v2

#3884 Release/1.55
  .github/workflows/release.yml
  .goreleaser.yml
  CHANGELOG.md
  build/PROMPT.md
  build/magefile.go
  build/release/release.go
  go.work.sum
Labels: size:L

#3885 chore: V2 UI segments
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  core/go.mod
  core/go.sum
  core/validation/flipt.cue
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/ext/common.go
  internal/storage/environments/fs/flipt/flags.go
  internal/storage/fs/snapshot.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/v2/environments/go.mod
  rpc/v2/environments/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  ui/src/app/flags/flagsApi.ts
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/flags/rulesApi.ts
  ui/src/app/segments/Segment.tsx
  ui/src/app/segments/Segments.tsx
  ui/src/app/segments/segmentsApi.ts
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/FlagFormContext.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/rules/MultiDistributionForm.tsx
  ui/src/components/rules/QuickEditRuleForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/SortableRule.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/components/variants/VariantForm.tsx
  ui/src/components/variants/Variants.tsx
  ui/src/store.ts
  ui/src/types/Constraint.ts
  ui/src/types/Distribution.ts
  ui/src/types/Evaluatable.ts
  ui/src/types/Flag.ts
  ui/src/types/Namespace.ts
  ui/src/types/Rollout.ts
  ui/src/types/Rule.ts
  ui/src/types/Segment.ts
  ui/src/types/Variant.ts
Labels: size:XL, v2

#3883 fix(build): rework test suite to compile for the new environments API
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  build/internal/cmd/azurite/main.go
  build/internal/cmd/gcs/main.go
  build/internal/cmd/loadtest/main.go
  build/internal/cmd/minio/main.go
  build/internal/flipt.go
  build/magefile.go
  build/main.go
  build/release/changelog.go
  build/release/release.go
  build/testing/cli.go
  build/testing/integration.go
  build/testing/integration/api/api.go
  build/testing/integration/authn/auth.go
  build/testing/integration/authz/auth.go
  build/testing/integration/environments/api.go
  build/testing/integration/environments/api_test.go
  build/testing/integration/environments/testdata/README.md
  build/testing/integration/integration.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/loadtest.go
  build/testing/migration.go
  build/testing/test.go
  build/testing/testdata/cli.txt
  build/testing/testdata/flipt-namespace-foo.yml
  build/testing/testdata/flipt-sorting.yml
  build/testing/testdata/flipt-yaml-stream.yml
  build/testing/testdata/flipt.yml
  build/testing/ui.go
  dagger.json
  go.work.sum
  sdk/go/v2/go.mod
  sdk/go/v2/go.sum
Labels: size:XXL

#3889 chore: V2 UI rollouts
  ui/src/app/flags/rolloutsApi.ts
  ui/src/app/flags/rules/Rules.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/components/rollouts/Rollout.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/rollouts/SortableRollout.tsx
  ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx
  ui/src/components/rules/QuickEditRuleForm.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/SortableRule.tsx
  ui/src/store.ts
  ui/src/types/Rollout.ts
Labels: size:XXL, v2

#3888 chore: make constraints act like variants on add/update/delete
  ui/src/app/flags/rolloutsApi.ts
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/constraints/Constraints.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/components/rollouts/Rollout.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/rollouts/SortableRollout.tsx
  ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx
  ui/src/components/rules/QuickEditRuleForm.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/SortableRule.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/segments/SegmentFormContext.tsx
  ui/src/components/variants/VariantForm.tsx
  ui/src/components/variants/Variants.tsx
  ui/src/store.ts
  ui/src/types/Rollout.ts
Labels: size:XXL, v2

#3903 chore: fixup namespaces/console, rm tokens in ui
  ui/src/App.tsx
  ui/src/app/Settings.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/namespaces/namespacesApi.ts
  ui/src/app/tokens/Tokens.tsx
  ui/src/app/tokens/tokensApi.ts
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/components/tokens/ShowTokenPanel.tsx
  ui/src/components/tokens/TokenForm.tsx
  ui/src/components/tokens/TokenTable.tsx
  ui/src/store.ts
  ui/src/types/Namespace.ts
Labels: size:XXL, v2

#3904 chore: bump ts version; install knip
  ui/package-lock.json
  ui/package.json
  ui/src/app/console/Console.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/components/Pagination.tsx
  ui/src/components/constraints/Constraints.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/rollouts/Rollouts.tsx
Labels: size:S, v2

#3906 chore: V2 UI ITs
  core/validation/flipt.cue
  internal/storage/environments/fs/flipt/flags.go
  ui/src/app/flags/Flag.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/tests/flags.spec.ts
  ui/tests/index.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/rollouts.spec.ts
  ui/tests/rules.spec.ts
  ui/tests/segments.spec.ts
  ui/tests/tokens.spec.ts
Labels: size:XL, v2

#3905 chore: add unsaved changes modal
  core/validation/flipt.cue
  internal/storage/environments/fs/flipt/flags.go
  ui/src/app/flags/Flag.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/assets/colors/dark.css
  ui/src/components/Footer.tsx
  ui/src/components/UnsavedChangesModal.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/tailwind.config.cjs
  ui/tests/flags.spec.ts
  ui/tests/index.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/rollouts.spec.ts
  ui/tests/rules.spec.ts
  ui/tests/segments.spec.ts
  ui/tests/tokens.spec.ts
Labels: size:XXL, v2

#3907 fix(build/its): get integration suite passing for base namespace and flag operations
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/go.mod
  build/go.sum
  build/internal/flipt.go
  build/testing/integration.go
  build/testing/integration/authn/auth.go
  build/testing/integration/authz/auth.go
  build/testing/integration/environments/api.go
  build/testing/integration/integration.go
  dagger.json
  internal/server/environments/storage.go
  internal/server/middleware/grpc/middleware.go
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/types/Rollout.ts
Labels: size:L

#3910 feat(ui): support larger screen widths
  ui/src/app/Layout.tsx
  ui/src/components/flags/FlagForm.tsx
Labels: size:XS

#3909 fix(ui): use segments instead of segmentKeys everywhere
  ui/src/app/Layout.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/types/Rollout.ts
Labels: size:M

#3911 chore: fix namespace update
  internal/storage/environments/fs/namespaces.go
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/namespaces/namespacesApi.ts
  ui/tests/namespaces.spec.ts
Labels: v2

#3912 feat(server): add list environments rpc
  internal/server/environments/server.go
  internal/server/environments/storage.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/environments.yaml
  rpc/v2/environments/environments_grpc.pb.go
  sdk/go/v2/environments.sdk.gen.go
  sdk/go/v2/http/environments.sdk.gen.go
Labels: size:XL

#3914 chore: V2 analytics
  PLAN.md
  internal/server/evaluation/evaluation.go
  internal/server/metrics/metrics.go
  internal/server/otel/attributes.go
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/rollouts/Rollout.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/rules/Rule.tsx
Labels: size:M

#3915 chore: add UI ITs for reordering/deleting rules and rollouts
  ui/src/components/UnsavedChangesModal.tsx
  ui/src/components/rollouts/Rollout.tsx
  ui/src/components/rollouts/SortableRollout.tsx
  ui/src/components/rules/Rule.tsx
  ui/src/components/rules/SortableRule.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/tests/rollouts.spec.ts
  ui/tests/rules.spec.ts
Labels: size:L

#3918 refactor(storage/git): remove gitfs and integrate storage/git/filesystem everywhere
  .github/workflows/proto.yml
  .github/workflows/test.yml
  _tools/go.sum
  buf.yaml
  cmd/flipt/server.go
  cmd/flipt/validate.go
  go.mod
  internal/config/credentials.go
  internal/gitfs/gitfs.go
  internal/gitfs/gitfs_test.go
  internal/gitfs/testdata/simple/four/five/six.txt
  internal/gitfs/testdata/simple/one.txt
  internal/gitfs/testdata/simple/two/three.txt
  internal/server/environments/server.go
  internal/server/evaluation/data/server.go
  internal/storage/analytics/file.go
  internal/storage/authn/memory/store.go
  internal/storage/authn/testing/testing.go
  internal/storage/environments/fs/core.go
  internal/storage/environments/fs/environment.go
  internal/storage/environments/git/store.go
  internal/storage/fs/snapshot.go
  internal/storage/git/filesystem.go
  internal/storage/git/filesystem_test.go
  internal/storage/git/metrics.go
  internal/storage/git/repository.go
  rpc/flipt/analytics/analytics.proto
  rpc/flipt/audit/event.proto
  rpc/flipt/auth/auth.proto
  rpc/flipt/evaluation/evaluation.proto
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.proto
  rpc/flipt/ofrep/ofrep.proto
Labels: size:XXL

#3917 v2: some unit test fixes
  config/flipt.schema.cue
  config/flipt.schema.json
  core/validation/validate_test.go
  internal/config/config.go
  internal/telemetry/telemetry_test.go
  internal/tracing/tracing_test.go
Labels: size:XXL

#3919 feat: V2 flipt server
  .devcontainer/Dockerfile
  .github/workflows/integration-test.yml
  DEPRECATIONS.md
  DEVELOPMENT.md
  Dockerfile
  Dockerfile.dev
  PLAN.md
  build/Dockerfile
  build/internal/flipt.go
  cmd/flipt/main.go
  magefile.go
Labels: size:L, v2

#3921 chore: mv one more update subs to defer
  internal/storage/git/repository.go
Labels: size:S

#3922 fix: V2 stuck mutex acq
  internal/storage/git/repository.go
Labels: size:S

#3924 fix: reinstate flipt v1 servives and add authz its
  .github/workflows/integration-test.yml
  build/testing/integration.go
  build/testing/integration/authn/auth.go
  build/testing/integration/environments/api.go
  build/testing/integration/integration.go
  build/testing/integration/readonly/testdata/alternate/.flipt.yml
  build/testing/integration/readonly/testdata/alternate/default.yaml
  build/testing/integration/readonly/testdata/alternate/production.yaml
  build/testing/integration/readonly/testdata/main/.flipt.yml
  build/testing/integration/testdata/alternative/features.yaml
  build/testing/integration/testdata/default/features.yaml
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/server/authn/server.go
  internal/server/flag.go
  internal/server/flag_test.go
  internal/server/server.go
Labels: size:L

#3920 chore: V2 UI radix refactor 1
  ui/package-lock.json
  ui/package.json
  ui/src/app/console/Console.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/Flags.tsx
  ui/src/app/flags/NewFlag.tsx
  ui/src/app/segments/NewSegment.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/app/segments/Segments.tsx
  ui/src/components/Dropdown.tsx
  ui/src/components/DropdownMenu.tsx
  ui/src/components/Modal.tsx
  ui/src/components/Page.tsx
  ui/src/components/Select.tsx
  ui/src/components/Skeleton.tsx
  ui/src/components/Slideover.tsx
  ui/src/components/TablePagination.tsx
  ui/src/components/TableSkeleton.tsx
  ui/src/components/TableViewOptions.tsx
  ui/src/components/UnsavedChangesModal.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/MetadataForm.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/panels/CopyToNamespacePanel.tsx
  ui/src/components/panels/DeletePanel.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/components/variants/VariantForm.tsx
Labels: size:XL

#3923 feat: namespace and env listbox refactor
  config/local.yml
  internal/config/environments.go
  internal/server/environments/server.go
  internal/server/environments/storage.go
  internal/storage/environments/git/store.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.proto
  ui/package-lock.json
  ui/package.json
  ui/src/app/Layout.tsx
  ui/src/app/environments/environmentsApi.ts
  ui/src/assets/colors/dark.css
  ui/src/components/Header.tsx
  ui/src/components/Nav.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/environments/EnvironmentListbox.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/src/index.css
  ui/src/store.ts
  ui/src/types/Environment.ts
Labels: size:XL

#3925 chore: fix config tests; make single env default; ensure atleast one default
  internal/config/config.go
  internal/config/config_test.go
  internal/config/environments.go
  internal/config/testdata/environments/no_default.yml
  internal/config/testdata/environments/single_is_default.yml
  internal/config/testdata/marshal/yaml/default.yml
Labels: size:M

#3926 chore: fix some minor ui issues
  config/local.yml
  ui/src/app/Settings.tsx
  ui/src/components/Page.tsx
  ui/src/components/command/CommandDialog.tsx
Labels: size:S

#3927 fix(storage/git): support fs.WalkDir and current dir path
  internal/server/environments/mock_environment.go
  internal/server/environments/storage.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/mock_environmentstore.go
  internal/server/evaluation/ofrep_bridge_test.go
  internal/server/evaluation/server.go
  internal/server/flag_test.go
  internal/server/server.go
  internal/storage/environments/environments.go
  internal/storage/fs/config.go
  internal/storage/git/filesystem.go
  internal/storage/git/filesystem_test.go
Labels: size:L

#3941 chore: fix more unit tests
  config/flipt.schema.cue
  config/flipt.schema.json
  config/schema_test.go
  internal/config/config_test.go
  internal/config/testdata/marshal/yaml/default.yml
  internal/info/flipt_test.go
  internal/server/authz/middleware/grpc/middleware_test.go
  internal/server/ofrep/evaluation_test.go
  internal/storage/analytics/migrator_test.go
  internal/storage/environments/fs/namespaces_test.go
  internal/storage/fs/snapshot_test.go
  rpc/flipt/auth/request.go
  rpc/flipt/request.go
  rpc/v2/environments/request.go
Labels: size:L
