Repository flipt-io/flipt, pull requests merged in 2025-06, with the labels that each got.

#4274 fix: v2 patch broken templates for propose changes
  internal/storage/fs/config.go
  internal/storage/fs/config_test.go
Labels: size:M, v2

#4273 refactor(ui): v2 use one style for dialogs
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/rollouts/Rollouts.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/Dialog.tsx
  ui/src/components/Modal.tsx
  ui/src/components/constraints/Constraints.tsx
  ui/src/components/environments/branches/CreateBranchPopover.tsx
  ui/src/components/environments/branches/CreateMergeProposalModal.tsx
  ui/src/components/environments/branches/DeleteBranchModal.tsx
  ui/src/components/panels/CopyToNamespacePanel.tsx
  ui/src/components/panels/DeletePanel.tsx
  ui/src/components/variants/Variants.tsx
Labels: size:XXL, v2

#4289 fix!(ofrep): v2 remove configuration endpoint as ofrep droped it from spec
  internal/server/evaluation/ofrep/server.go
  internal/server/evaluation/ofrep/server_test.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/ofrep/ofrep.pb.gw.go
  rpc/flipt/ofrep/ofrep.proto
  rpc/flipt/ofrep/ofrep_grpc.pb.go
  rpc/flipt/openapi.yaml
Labels: size:XL, v2

#4295 chore: Release/1.58.4
  CHANGELOG.md
  go.work.sum
Labels: size:S

#4309 fix: Push on branch
  internal/storage/environments/git/store.go
  internal/storage/environments/git/store_test.go
  internal/storage/git/metrics.go
  internal/storage/git/repository.go
  ui/src/components/environments/branches/CreateBranchPopover.tsx
Labels: size:M

#4287 feat(scm): v2 support gitea as scm
  .mockery.yml
  codecov.yml
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/config/environments.go
  internal/enterprise/storage/environments/git/gitea/gitea.go
  internal/enterprise/storage/environments/git/gitea/gitea_mock.go
  internal/enterprise/storage/environments/git/gitea/gitea_test.go
  internal/server/environments/environments_mock.go
  internal/storage/environments/environments.go
  internal/storage/environments/environments_test.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/openapi.yaml
Labels: size:XL, v2

#4341 chore: update inapp links for v2 docs
  ui/src/app/NotFoundLayout.tsx
  ui/src/app/Support.tsx
  ui/src/app/analytics/Analytics.tsx
  ui/src/app/auth/Login.tsx
  ui/src/app/flags/NewFlag.tsx
  ui/src/app/segments/NewSegment.tsx
  ui/src/components/environments/branches/CreateBranchPopover.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/variants/VariantForm.tsx
  ui/tests/support.spec.ts
Labels: size:M

#4343 fix(csrf): update middleware usage to comply with gorilla/csrf changes
  .gitignore
  config/flipt.schema.cue
  config/flipt.schema.json
  go.work.sum
  internal/cmd/http.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
Labels: bug, needs docs, size:M

#4362 V2 quickstart cmd
  cmd/flipt/main.go
  cmd/flipt/quickstart.go
  internal/cmd/util/browser.go
Labels: size:L

#4381 fix: just show segment name in segment picker
  go.work.sum
  ui/src/components/Combobox.tsx
  ui/src/components/rules/forms/SingleDistributionForm.tsx
Labels: size:S

#4384 fix: flag metadata parsing from snapshot
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  internal/storage/fs/testdata/valid/explicit_index/prod/prod.features.yml
Labels: automerge, size:S
