Repository flipt-io/flipt, pull requests merged in 2025-05, with the labels that each got.

#4138 refactor(ui): rework listbox
  ui/package-lock.json
  ui/package.json
  ui/src/components/Header.tsx
  ui/src/components/environments/EnvironmentListbox.tsx
  ui/src/components/forms/Listbox.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/tests/flags.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/segments.spec.ts
Labels: size:L

#4145 chore: V2 debug logging remote
  internal/storage/git/repository.go
Labels: size:M

#4147 chore: add fuzztest; remove unused testdata
  .gitignore
  internal/config/config_fuzz_test.go
  internal/config/testdata/storage/azblob_full.yml
  internal/config/testdata/storage/azblob_invalid.yml
  internal/config/testdata/storage/gs_full.yml
  internal/config/testdata/storage/gs_invalid.yml
  internal/config/testdata/storage/invalid_object_storage_type_not_specified.yml
  internal/config/testdata/storage/oci_invalid_manifest_version.yml
  internal/config/testdata/storage/oci_invalid_no_repo.yml
  internal/config/testdata/storage/oci_invalid_unexpected_scheme.yml
  internal/config/testdata/storage/oci_provided.yml
  internal/config/testdata/storage/oci_provided_aws_ecr.yml
  internal/config/testdata/storage/oci_provided_full.yml
  internal/config/testdata/storage/oci_provided_invalid_auth.yml
  internal/config/testdata/storage/oci_provided_no_auth.yml
  internal/config/testdata/storage/s3_bucket_missing.yml
  internal/config/testdata/storage/s3_full.yml
  internal/config/testdata/storage/s3_provided.yml
Labels: size:L

#4151 docs: update Contributing section in README to link DEVELOPMENT.md R…
  README.md
Labels: automerge, size:XS

#4148 fix: segment picker bugs
  ui/src/components/Combobox.tsx
  ui/src/components/forms/SegmentsPicker.tsx
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rules/MultiDistributionForm.tsx
  ui/src/components/rules/QuickEditRuleForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/utils/formik-helpers.ts
Labels: size:XXL

#4149 fix: give combobox relative width
  ui/src/components/Combobox.tsx
Labels: size:L

#4150 V2 fix analytics
  internal/cmd/http.go
  internal/server/analytics/clickhouse/mutation.go
  internal/server/metrics/metrics.go
  internal/server/tracing/attributes.go
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/analytics/analytics.pb.gw.go
  rpc/flipt/analytics/analytics.proto
  rpc/flipt/flipt.yaml
  rpc/flipt/openapi.yaml
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/app/flags/analyticsApi.tsx
  ui/src/data/api.ts
  ui/vite.config.ts
Labels: size:L

#4172 feat: update settings page; use tanstack table for constraints/variants
  ui/src/app/Settings.tsx
  ui/src/app/preferences/Preferences.tsx
  ui/src/app/preferences/preferencesSlice.ts
  ui/src/components/Chips.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/constraints/ConstraintTable.tsx
  ui/src/components/constraints/Constraints.tsx
  ui/src/components/forms/Select.tsx
  ui/src/components/namespaces/NamespaceTable.tsx
  ui/src/components/variants/VariantTable.tsx
  ui/src/components/variants/Variants.tsx
  ui/src/data/hooks/notification.ts
  ui/tests/namespaces.spec.ts
  ui/tests/preferences.spec.ts
Labels: size:XXL, v2

#4181 fix: issue where updating namespace deletes all its data
  internal/storage/environments/fs/namespaces.go
  internal/storage/environments/fs/namespaces_test.go
Labels: size:L, v2

#4175 refactor(ui): combine onboarding and support page
  ui/src/App.tsx
  ui/src/app/Onboarding.tsx
  ui/src/app/Support.tsx
  ui/tests/flags.spec.ts
  ui/tests/onboarding.spec.ts
Labels: size:L

#4184 fix: prune remotes from cache that no longer exist
  go.work.sum
  internal/storage/fs/cache.go
  internal/storage/fs/cache_test.go
  internal/storage/fs/git/store.go
Labels: automerge, size:L

#4185 chore: fix double evict; turn log down to warn
  go.work.sum
  internal/storage/fs/cache.go
  internal/storage/fs/poll.go
Labels: automerge

#4155 refactor(ui): rework combobox
  ui/package-lock.json
  ui/package.json
  ui/src/app/console/Console.tsx
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/components/Button.tsx
  ui/src/components/Combobox.tsx
  ui/src/components/Command.tsx
  ui/src/components/Dialog.tsx
  ui/src/components/Popover.tsx
  ui/src/components/forms/SegmentsPicker.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/components/rules/MultiDistributionForm.tsx
  ui/src/components/rules/QuickEditRuleForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/rules/SingleDistributionForm.tsx
  ui/src/index.css
  ui/src/types/Flag.ts
  ui/src/types/Segment.ts
  ui/src/types/Selectable.ts
  ui/src/types/Variant.ts
  ui/src/utils/helpers.ts
  ui/tests/rules.spec.ts
Labels: size:XL

#4201 V2 streaming metrics
  internal/server/evaluation/client/server.go
  internal/server/evaluation/client/server_test.go
  internal/server/metrics/metrics.go
Labels: size:L

#4202 chore: make keys lowercase in ui
  ui/src/utils/helpers.test.ts
  ui/src/utils/helpers.ts
Labels: size:S

#4188 refactor(ui): v2 new layout
  ui/index.html
  ui/package-lock.json
  ui/package.json
  ui/src/App.tsx
  ui/src/app/Layout.tsx
  ui/src/app/analytics/Analytics.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/app/preferences/preferencesSlice.ts
  ui/src/assets/colors/dark.css
  ui/src/assets/colors/light.css
  ui/src/components/AppSidebar.tsx
  ui/src/components/Combobox.tsx
  ui/src/components/Header.tsx
  ui/src/components/NamespaceSwitcher.tsx
  ui/src/components/Nav.tsx
  ui/src/components/NavMain.tsx
  ui/src/components/NavSecondary.tsx
  ui/src/components/NavUser.tsx
  ui/src/components/Popover.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/Slideover.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/environments/EnvironmentListbox.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/forms/SegmentsPicker.tsx
  ui/src/components/header/Notifications.tsx
  ui/src/components/header/UserProfile.tsx
  ui/src/components/json/JsonEditor.tsx
  ui/src/components/panels/CopyToNamespacePanel.tsx
  ui/src/components/panels/DeletePanel.tsx
  ui/src/components/ui/avatar.tsx
  ui/src/components/ui/button.tsx
  ui/src/components/ui/dropdown-menu.tsx
  ui/src/components/ui/input.tsx
  ui/src/components/ui/separator.tsx
  ui/src/components/ui/sheet.tsx
  ui/src/components/ui/sidebar.tsx
  ui/src/components/ui/skeleton.tsx
  ui/src/components/ui/tooltip.tsx
  ui/src/data/hooks/error.ts
  ui/src/data/hooks/notification.ts
  ui/src/data/hooks/success.ts
  ui/src/hooks/use-mobile.ts
  ui/src/index.css
  ui/src/types/Preferences.ts
  ui/tests/flags.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/onboarding.spec.ts
  ui/tests/rules.spec.ts
  ui/tests/segments.spec.ts
Labels: size:XXL

#4205 refactor(ui): v2 use the same icons
  ui/package.json
  ui/src/app/NotFoundLayout.tsx
  ui/src/app/Support.tsx
  ui/src/app/analytics/Analytics.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/components/Banner.tsx
  ui/src/components/Button.tsx
  ui/src/components/Pagination.tsx
  ui/src/components/Searchbox.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/flags/MetadataForm.tsx
  ui/src/components/forms/SegmentsPicker.tsx
  ui/src/components/forms/Tags.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/variants/VariantForm.tsx
Labels: size:L

#4208 fix: evaluation console and evaluation with envs
  go.work.sum
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_test.go
  ui/src/app/console/Console.tsx
Labels: size:L

#4152 feat: V2 batch analytics
  .mockery.yml
  _tools/go.mod
  _tools/go.sum
  go.mod
  go.work.sum
  internal/migrations/clickhouse/20250121202326_create_table_counter_aggregated_analytics.up.sql
  internal/migrations/clickhouse/20250121202552_create_view_counter_aggregated_analytics.up.sql
  internal/server/analytics/analytics.go
  internal/server/analytics/analytics_mock.go
  internal/server/analytics/analytics_test.go
  internal/server/analytics/clickhouse/client.go
  internal/server/analytics/prometheus/client.go
  internal/server/analytics/prometheus/client_test.go
  internal/server/analytics/prometheus/mock_prometheusClient_test.go
  internal/server/analytics/prometheus/prometheus_mock.go
  internal/server/analytics/server.go
  internal/server/analytics/server_test.go
  rpc/v2/analytics/analytics.pb.go
  rpc/v2/analytics/analytics.pb.gw.go
  rpc/v2/analytics/analytics.proto
  rpc/v2/analytics/analytics_grpc.pb.go
  ui/package-lock.json
  ui/package.json
  ui/src/app/flags/analyticsApi.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/types/Analytics.ts
Labels: size:XXL

#4212 feat: port over redis cluster and prefix
  config/flipt.schema.cue
  config/flipt.schema.json
  core/validation/flipt.cue
  core/validation/flipt.json
  go.mod
  go.sum
  internal/cmd/authn.go
  internal/config/authentication.go
  internal/storage/authn/redis/client.go
  internal/storage/authn/redis/client_test.go
  internal/storage/authn/redis/store.go
  internal/storage/authn/redis/store_test.go
  ui/src/app/auth/Login.tsx
Labels: size:XL

#4213 chore: run gopls modernize
  internal/cmd/grpc.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/log.go
  internal/config/metrics.go
  internal/gateway/marshaller.go
  internal/server/analytics/clickhouse/client.go
  internal/server/analytics/clickhouse/mutation.go
  internal/server/analytics/prometheus/client.go
  internal/server/authn/method/oidc/server.go
  internal/server/authn/method/oidc/server_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
  internal/server/authz/engine/rego/engine.go
  internal/server/authz/engine/rego/engine_test.go
  internal/server/authz/middleware/grpc/middleware.go
  internal/server/authz/middleware/grpc/middleware_test.go
  internal/server/middleware/grpc/middleware_test.go
  internal/storage/analytics/fields.go
  internal/storage/authn/redis/store.go
  internal/storage/authn/testing/testing.go
  internal/storage/environments/fs/flipt/flags.go
  internal/storage/environments/fs/flipt/flags_test.go
  internal/storage/environments/fs/flipt/segments.go
  internal/storage/fs/snapshot_test.go
  internal/storage/git/filesystem.go
Labels: automerge, size:L

#4211 refactor(ui): v2 new layout for flags with analytics
  ui/src/app/flags/Flag.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/Header.tsx
  ui/src/components/environments/EnvironmentRemoteInfo.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/components/ui/button.tsx
  ui/src/index.css
Labels: size:L

#4226 fix(ui/v2): fix the header separator and analytics tooltip on Flags page
  ui/src/app/Layout.tsx
  ui/src/components/Header.tsx
  ui/src/components/environments/EnvironmentRemoteInfo.tsx
  ui/src/components/flags/FlagTable.tsx
Labels: size:M

#4229 fix(audit): keep segment data for rollout and rule
  go.work.sum
  internal/server/audit/types.go
  internal/server/audit/types_test.go
Labels: size:L

#4228 ci(v2): migrate to go tool
  _tools/go.mod
  _tools/go.sum
  _tools/tools.go
  go.mod
  go.sum
  go.work
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/server/analytics/prometheus/prometheus_mock.go
  internal/server/authz/middleware/grpc/middleware.go
  internal/storage/environments/fs/flipt/flags.go
  internal/storage/environments/fs/flipt/segments.go
  magefile.go
Labels: size:L

#4231 fix(storage): map protobuf enums to ints in sql updates for rule and rollout
  internal/storage/sql/common/rollout.go
  internal/storage/sql/common/rule.go
Labels: size:XS

#4232 V2 branch 2
  .gitignore
  go.work.sum
  internal/server/analytics/prometheus/prometheus_mock.go
  internal/server/environments/environments_mock.go
  internal/server/environments/server.go
  internal/server/environments/storage.go
  internal/storage/environments/git/readonly.go
  internal/storage/environments/git/readonly_test.go
  internal/storage/environments/git/store.go
  internal/storage/environments/git/store_test.go
  magefile.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/openapi.yaml
  ui/src/app/environments/environmentsApi.ts
  ui/src/app/namespaces/namespacesApi.ts
  ui/src/components/AppSidebar.tsx
  ui/src/components/Combobox.tsx
  ui/src/components/Header.tsx
  ui/src/components/environments/EnvironmentBranchSelector.tsx
  ui/src/components/environments/EnvironmentNamespaceSwitcher.tsx
  ui/src/components/environments/EnvironmentRemoteInfo.tsx
  ui/src/types/Environment.ts
Labels: size:XL

#4233 chore: test with prepared statements off for pg
  .github/workflows/integration-test.yml
  build/testing/integration.go
  internal/storage/authn/sql/store.go
  internal/storage/sql/common/segment.go
  internal/storage/sql/fields.go
Labels: automerge, size:M

#4234 Release/1.58
  CHANGELOG.md
Labels: size:XS

#4236 fix(ui): v2 clean up branch selector
  ui/src/components/Button.tsx
  ui/src/components/Combobox.tsx
  ui/src/components/Select.tsx
  ui/src/components/environments/EnvironmentBranchSelector.tsx
  ui/src/components/forms/SegmentsPicker.tsx
  ui/src/components/forms/Select.tsx
  ui/src/components/ui/button.tsx
Labels: size:M

#4240 fix(ui): v2 clean the styles and refine some texts on support page
  ui/src/app/Support.tsx
Labels: size:M

#4254 Release/1.58
  CHANGELOG.md
Labels: size:XS

#4237 feat: V2 proposals
  .mockery.yml
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/config/config_test.go
  internal/config/environments.go
  internal/config/testdata/environments/invalid_scm.yml
  internal/config/testdata/environments/valid_scm.yml
  internal/enterprise/storage/environments/git/github/github.go
  internal/enterprise/storage/environments/git/github/github_mock.go
  internal/enterprise/storage/environments/git/github/github_test.go
  internal/enterprise/storage/environments/git/scm.go
  internal/enterprise/storage/environments/git/scm_test.go
  internal/enterprise/storage/environments/git/store.go
  internal/server/environments/environments_mock.go
  internal/server/environments/server.go
  internal/server/environments/storage.go
  internal/storage/environments/environments.go
  internal/storage/environments/git/store.go
  internal/storage/environments/git/store_test.go
  internal/storage/fs/config.go
  internal/storage/fs/local/poll.go
  internal/storage/fs/local/testdata/staging/.gitkeep
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/environments_grpc.pb.go
  rpc/v2/environments/openapi.yaml
  sdk/go/v2/http/environments.sdk.gen.go
  ui/src/app/environments/environmentsApi.ts
  ui/src/components/Header.tsx
  ui/src/components/Modal.tsx
  ui/src/components/environments/CreateBranchPopover.tsx
  ui/src/components/environments/CreateMergeProposalModal.tsx
  ui/src/components/environments/EnvironmentNamespaceSwitcher.tsx
  ui/src/components/environments/EnvironmentProposalStatus.tsx
  ui/src/components/ui/button.tsx
  ui/src/types/Change.ts
  ui/src/types/Environment.ts
Labels: size:XXL

#4266 chore: v2 upgrade node from v18 to v22
  build/internal/ui.go
  build/testing/ui.go
  ui/Dockerfile
Labels: automerge, size:XS, v2

#4268 v2: Upgrade OPA
  go.mod
  go.sum
  go.work.sum
  internal/server/authz/engine/rego/engine.go
  rpc/v2/environments/request.go
Labels: size:M, v2

#4270 fix(ui): v2 use the same style for dropdown
  ui/src/components/Dropdown.tsx
Labels: size:S

#4272 fix: disallow branches with existing env name
  internal/server/environments/storage.go
  ui/src/components/environments/branches/CreateBranchButton.tsx
  ui/src/components/environments/branches/CreateBranchPopover.tsx
  ui/src/components/ui/button.tsx
  ui/tests/branches.spec.ts
Labels: size:L, v2
