Repository flipt-io/flipt, pull requests merged in 2025-04, with the labels that each got.

#4019 chore: Update nextjs example deps
  examples/nextjs/app-router/README.md
  examples/nextjs/app-router/next.config.mjs
  examples/nextjs/app-router/package-lock.json
  examples/nextjs/app-router/package.json
  examples/nextjs/app-router/src/app/actions/getGreeting.ts
  examples/nextjs/app-router/tsconfig.json
  examples/nextjs/pages-router/README.md
  examples/nextjs/pages-router/next.config.mjs
  examples/nextjs/pages-router/package-lock.json
  examples/nextjs/pages-router/package.json
  examples/nextjs/pages-router/pages/api/hello.ts
  examples/nextjs/pages-router/pages/index.tsx
  examples/nextjs/pages-router/tsconfig.json
Labels: size:L

#4018 feat: add contains constraint type
  internal/server/evaluation/legacy_evaluator.go
  internal/server/evaluation/legacy_evaluator_test.go
  rpc/flipt/operators.go
  ui/src/types/Constraint.ts
Labels: automerge, size:L

#4034 feat(cache): support optional prefix for redis cache keys
  config/flipt.schema.cue
  config/flipt.schema.json
  go.work.sum
  internal/cache/cache.go
  internal/cache/memory/cache.go
  internal/cache/redis/cache.go
  internal/cache/redis/cache_test.go
  internal/config/cache.go
  internal/config/server.go
Labels: automerge, needs docs, size:L

#4035 feat: Support Redis cluster
  config/flipt.schema.cue
  config/flipt.schema.json
  core/validation/flipt.cue
  core/validation/flipt.json
  go.mod
  go.sum
  internal/cache/redis/client.go
  internal/cache/redis/client_test.go
  internal/cmd/grpc.go
  internal/config/cache.go
  internal/config/config.go
  internal/config/config_test.go
  internal/storage/cache/cache_test.go
  internal/telemetry/telemetry_test.go
Labels: needs docs, size:L

#4042 chore: update changelog for 1.57 release
  CHANGELOG.md
Labels: size:XS

#4053 fix(ui): display missing shadows in dark mode with tailwind v4
  ui/src/assets/colors/dark.css
Labels: size:XS

#4054 chore(deps/v2): upgrade tailwind to v4
  ui/index.dev.html
  ui/index.html
  ui/package-lock.json
  ui/package.json
  ui/postcss.config.cjs
  ui/src/app/ErrorLayout.tsx
  ui/src/app/Layout.tsx
  ui/src/app/NotFoundLayout.tsx
  ui/src/app/Onboarding.tsx
  ui/src/app/Support.tsx
  ui/src/app/auth/Login.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/assets/colors/dark.css
  ui/src/components/Badge.tsx
  ui/src/components/Button.tsx
  ui/src/components/Combobox.tsx
  ui/src/components/DropdownMenu.tsx
  ui/src/components/EmptyState.tsx
  ui/src/components/Header.tsx
  ui/src/components/Modal.tsx
  ui/src/components/Nav.tsx
  ui/src/components/Searchbox.tsx
  ui/src/components/Select.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/Switch.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/environments/EnvironmentListbox.tsx
  ui/src/components/forms/Input.tsx
  ui/src/components/forms/JsonTextArea.tsx
  ui/src/components/forms/Listbox.tsx
  ui/src/components/forms/Select.tsx
  ui/src/components/forms/Tags.tsx
  ui/src/components/forms/TextArea.tsx
  ui/src/components/forms/Toggle.tsx
  ui/src/components/header/Notifications.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/namespaces/NamespaceListbox.tsx
  ui/src/components/notifications/ErrorNotification.tsx
  ui/src/components/notifications/SuccessNotification.tsx
  ui/src/components/panels/CopyToNamespacePanel.tsx
  ui/src/components/panels/DeletePanel.tsx
  ui/src/components/rollouts/EditRolloutForm.tsx
  ui/src/components/rollouts/QuickEditRolloutForm.tsx
  ui/src/components/rollouts/RolloutForm.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/rules/MultiDistributionForm.tsx
  ui/src/components/rules/QuickEditRuleForm.tsx
  ui/src/components/rules/RuleForm.tsx
  ui/src/components/segments/ConstraintForm.tsx
  ui/src/components/variants/VariantForm.tsx
  ui/src/index.css
  ui/tailwind.config.cjs
Labels: size:L

#4060 feat: add back ability to disable UI via config
  DEPRECATIONS.md
  config/flipt.schema.json
  internal/cmd/http.go
  internal/config/config.go
  internal/config/testdata/marshal/yaml/default.yml
  internal/config/ui.go
Labels: automerge, size:M

#4061 fix(store): disable modification of the store in read only mode
  internal/cmd/grpc.go
  internal/storage/unmodifiable/store.go
  internal/storage/unmodifiable/store_test.go
Labels: size:L

#4063 chore: prep for 1.58 release
  CHANGELOG.md
Labels: size:S

#3949 feat: move over ofrep and eval snapshot impl
  .github/workflows/integration-test.yml
  build/README.md
  build/testing/integration.go
  build/testing/integration/integration.go
  build/testing/integration/snapshot/snapshot_test.go
  build/testing/integration/testdata/alternative/features.yaml
  config/local.yml
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/ext/common.go
  internal/server/authn/method/token/server.go
  internal/server/authn/method/token/server_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
  internal/server/authn/server.go
  internal/server/authn/server_test.go
  internal/server/evaluation/data/server.go
  internal/server/evaluation/ofrep/middleware.go
  internal/server/evaluation/ofrep/middleware_test.go
  internal/server/evaluation/ofrep/server.go
  internal/server/evaluation/ofrep/server_test.go
  internal/server/evaluation/ofrep_bridge.go
  internal/server/evaluation/ofrep_bridge_test.go
  internal/server/evaluation/server.go
  internal/server/evaluation/server_test.go
  internal/server/ofrep/errors.go
  internal/server/ofrep/evaluation.go
  internal/server/ofrep/evaluation_test.go
  internal/server/ofrep/extensions.go
  internal/server/ofrep/mock_bridge.go
  internal/server/ofrep/server.go
  internal/server/ofrep/server_test.go
  internal/server/server.go
  internal/storage/fs/snapshot.go
  internal/storage/fs/snapshot_test.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/ofrep/ofrep.proto
  rpc/flipt/ofrep/ofrep_grpc.pb.go
Labels: size:XXL

#4068 feat: V2 env eval
  CHANGELOG.md
  build/testing/integration.go
  build/testing/integration/authn/auth.go
  build/testing/integration/authz/auth.go
  build/testing/integration/environments/api.go
  build/testing/integration/integration.go
  config/local.yml
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/common/context.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/cors.go
  internal/config/environments.go
  internal/config/testdata/environments/shared_storage_different_directories.yml
  internal/config/testdata/environments/shared_storage_no_directories.yml
  internal/config/testdata/environments/shared_storage_same_directory.yml
  internal/config/testdata/marshal/yaml/default.yml
  internal/ext/common.go
  internal/server/common/common.go
  internal/server/environments/mock_environment.go
  internal/server/environments/storage.go
  internal/server/evaluation/data/server.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/mock_environmentstore.go
  internal/server/evaluation/ofrep_bridge.go
  internal/server/evaluation/ofrep_bridge_test.go
  internal/server/evaluation/server.go
  internal/server/flag_test.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/server/server.go
  internal/storage/environments/environments.go
  internal/storage/environments/fs/flipt/common.go
  internal/storage/environments/fs/namespaces.go
  internal/storage/fs/snapshot.go
  internal/storage/mock_readonlystore.go
  internal/storage/storage.go
  rpc/flipt/request.go
  ui/src/app/Layout.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/preferences/Preferences.tsx
  ui/src/data/api.ts
  ui/tests/flags.spec.ts
  ui/tests/namespaces.spec.ts
  ui/tests/segments.spec.ts
Labels: size:XXL

#4085 chore: go 1.24
  .devcontainer/Dockerfile
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/nightly.yml
  .github/workflows/proto-push.yml
  .github/workflows/proto.yml
  .github/workflows/release-tag-latest.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .github/workflows/test.yml
  .golangci.yml
  DEVELOPMENT.md
  Dockerfile
  Dockerfile.dev
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  build/internal/flipt.go
  build/main.go
  build/testing/integration.go
  build/testing/ui.go
  core/go.mod
  core/go.sum
  go.mod
  go.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/storage/analytics/fields_test.go
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/core/core.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/options/options.pb.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/go.mod
  rpc/v2/environments/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/v2/go.mod
  sdk/go/v2/go.sum
  ui/tests/namespaces.spec.ts
Labels: automerge, size:L

#4082 feat: V2 env analytics
  internal/metrics/metrics.go
  internal/migrations/clickhouse/20250121202120_create_table_counter_analytics.down.sql
  internal/migrations/clickhouse/20250121202120_create_table_counter_analytics.up.sql
  internal/migrations/clickhouse/20250121202326_create_table_counter_aggregated_analytics.down.sql
  internal/migrations/clickhouse/20250121202326_create_table_counter_aggregated_analytics.up.sql
  internal/migrations/clickhouse/20250121202552_create_view_counter_aggregated_analytics.down.sql
  internal/migrations/clickhouse/20250121202552_create_view_counter_aggregated_analytics.up.sql
  internal/server/analytics/analytics.go
  internal/server/analytics/analytics_test.go
  internal/server/analytics/clickhouse/client.go
  internal/server/analytics/clickhouse/client_test.go
  internal/server/analytics/clickhouse/mutation.go
  internal/server/analytics/prometheus/client.go
  internal/server/analytics/prometheus/client_test.go
  internal/server/analytics/server.go
  internal/server/analytics/server_test.go
  internal/server/analytics/sink.go
  internal/server/environments/mock_environment.go
  internal/server/environments/server.go
  internal/server/environments/storage.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/ofrep_bridge.go
  internal/server/evaluation/ofrep_bridge_test.go
  internal/server/evaluation/server.go
  internal/server/metrics/metrics.go
  internal/server/middleware/grpc/middleware.go
  internal/server/middleware/grpc/middleware_test.go
  internal/storage/environments/git/store.go
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/analytics/analytics.proto
  rpc/flipt/evaluation/evaluation.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.proto
  ui/src/App.tsx
  ui/src/app/Layout.tsx
  ui/src/app/console/Console.tsx
  ui/src/app/environments/environmentsApi.ts
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/components/environments/EnvironmentListbox.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/namespaces/NamespaceForm.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/data/api.ts
  ui/src/types/Environment.ts
Labels: automerge, size:XL

#4094 fix: logout in ui error
  internal/cmd/authn.go
  internal/storage/authn/auth.go
  internal/storage/authn/memory/store.go
  internal/storage/authn/redis/store.go
Labels: size:S

#4095 fix: issue with redis not setting expires at on auth record
  internal/storage/authn/memory/store.go
  internal/storage/authn/redis/store.go
  internal/storage/authn/testing/testing.go
Labels: size:M

#4096 chore(tracing): drop unused code for Jaeger and Zipkin configuration
  internal/config/tracing.go
Labels: size:S

#4090 chore: generate openapi docs again
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/storage/environments/environments.go
  openapi.yaml
  rpc/flipt/buf.gen.yaml
  rpc/flipt/openapi.yaml
  rpc/v2/environments/buf.gen.yaml
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/environments.yaml
  rpc/v2/environments/openapi.yaml
  sdk/go/v2/http/environments.sdk.gen.go
  ui/src/data/api.ts
  ui/vite.config.ts
Labels: size:XXL

#4101 ci: bump golangci-lint to v2
  .github/workflows/lint.yml
  .golangci.yml
  _tools/go.mod
  _tools/tools.go
  go.work.sum
  internal/server/authn/method/http.go
  internal/server/authn/middleware/http/middleware_test.go
  internal/server/evaluation/evaluation.go
  internal/storage/authn/testing/testing.go
  internal/storage/list.go
  magefile.go
Labels: size:L

#4098 chore: prep for v2 packaging/release
  .github/workflows/nightly.yml
  .github/workflows/post-release.yml
  .github/workflows/proto-push.yml
  .github/workflows/release-clients.yml
  .github/workflows/release-tag-latest.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .goreleaser.darwin.yml
  .goreleaser.linux.yml
  .goreleaser.nightly.yml
  .goreleaser.yml
  build/Dockerfile
  build/main.go
  cmd/flipt/main.go
  config/production.yml
  dagger.json
  install.sh
  ui/src/app/Layout.tsx
  ui/src/components/Header.tsx
Labels: size:L

#4100 feat: work toward auto instrumentation for otel
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  config/flipt.schema.cue
  config/flipt.schema.json
  core/go.mod
  core/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/cmd/grpc.go
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/metrics.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/metrics/otlp.yml
  internal/config/testdata/tracing/otlp.yml
  internal/config/testdata/tracing/wrong_propagator.yml
  internal/config/testdata/tracing/wrong_sampling_ratio.yml
  internal/config/tracing.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  internal/tracing/tracing.go
  internal/tracing/tracing_test.go
  rpc/flipt/analytics/analytics.pb.gw.go
  rpc/flipt/auth/auth.pb.gw.go
  rpc/flipt/evaluation/evaluation.pb.gw.go
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/meta/meta.pb.gw.go
  rpc/flipt/meta/meta.proto
  rpc/flipt/ofrep/ofrep.pb.gw.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/go.mod
  rpc/v2/environments/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/v2/go.mod
  sdk/go/v2/go.sum
Labels: size:XL

#4118 feat: add otel logs exporter
  cmd/flipt/main.go
  go.mod
  go.sum
  internal/cmd/grpc.go
  internal/otel/logs/logs.go
  internal/otel/metrics/metrics.go
  internal/otel/metrics/metrics_test.go
  internal/otel/resource.go
  internal/otel/resource_test.go
  internal/otel/traces/tracing.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/ofrep_bridge.go
  internal/server/metrics/metrics.go
  internal/server/otel/noop_exporter.go
  internal/server/otel/noop_provider.go
  internal/server/tracing/attributes.go
  internal/storage/git/metrics.go
  internal/tracing/tracing.go
Labels: size:L

#4120 fix: ui shadow missing in v2; remove unused authz configs for now
  internal/config/authentication.go
  internal/config/authorization.go
  ui/src/assets/colors/dark.css
Labels: automerge, size:L

#4122 fix: issue with z-index in layout/banner; color issues with env listbox
  ui/src/app/Layout.tsx
  ui/src/components/environments/EnvironmentListbox.tsx
Labels: size:M

#4123 V2 major UI overhaul
  ui/src/app/console/Console.tsx
  ui/src/app/flags/Flag.tsx
  ui/src/app/flags/Flags.tsx
  ui/src/app/flags/analytics/Analytics.tsx
  ui/src/app/flags/rules/Rules.tsx
  ui/src/app/namespaces/Namespaces.tsx
  ui/src/app/segments/Segment.tsx
  ui/src/app/segments/Segments.tsx
  ui/src/assets/colors/dark.css
  ui/src/assets/colors/light.css
  ui/src/components/Badge.tsx
  ui/src/components/Button.tsx
  ui/src/components/Combobox.tsx
  ui/src/components/EmptyState.tsx
  ui/src/components/Page.tsx
  ui/src/components/Searchbox.tsx
  ui/src/components/Select.tsx
  ui/src/components/TablePagination.tsx
  ui/src/components/TagBadge.tsx
  ui/src/components/Well.tsx
  ui/src/components/constraints/Constraints.tsx
  ui/src/components/flags/FlagForm.tsx
  ui/src/components/flags/FlagFormContext.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/FlagTypeBadge.tsx
  ui/src/components/forms/Input.tsx
  ui/src/components/forms/TextArea.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/src/components/segments/SegmentForm.tsx
  ui/src/components/segments/SegmentMatchTypeBadge.tsx
  ui/src/components/segments/SegmentTable.tsx
  ui/src/components/variants/Variants.tsx
  ui/src/index.css
Labels: size:XXL

#4125 fix: small ui issues, z-index; move rollouts page to proper place
  ui/src/app/Layout.tsx
  ui/src/app/flags/rollouts/Rollouts.tsx
  ui/src/components/flags/FlagForm.tsx
Labels: size:XS

#4139 chore: change v2 nightly to v2 alpha
  .github/workflows/alpha.yml
  .goreleaser.darwin.yml
  .goreleaser.linux.yml
  .goreleaser.nightly.yml
  .goreleaser.yml
  cmd/flipt/main.go
Labels: size:M

#4142 chore: V2 banner
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/images/v2-banner.svg
  README.md
Labels: size:M
