Repository flipt-io/flipt, pull requests merged in 2025-01, with the labels that each got.

#3775 chore: prep 1.54 for release
  CHANGELOG.md
  go.mod
  go.sum
  go.work.sum
  sdk/go/go.mod
  sdk/go/go.sum
Labels: automerge

#3791 fix: update flag with no metadata
  go.work.sum
  ui/src/app/flags/flagsApi.ts
Labels: automerge

#3792 chore: Add back release footer
  .github/workflows/release.yml
  .goreleaser.yml
  CHANGELOG.md
Labels: automerge

#3808 fix: bucket prefix
  go.work.sum
  internal/storage/fs/object/store.go
  internal/storage/fs/object/store_test.go
  internal/storage/fs/store/store.go
Labels: automerge

#3809 chore(deps): go work sync
  _tools/go.mod
  _tools/go.sum
  build/go.mod
  build/go.sum
  core/go.mod
  core/go.sum
  examples/basic/go.mod
  examples/basic/go.sum
  examples/openfeature/go.mod
  examples/openfeature/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/options/options.pb.go
  sdk/go/go.mod
  sdk/go/go.sum
Labels: size:L

#3827 fix(audit): allow to send events with complex payload to kafka with avro
  examples/audit/kafka/README.md
  examples/audit/kafka/docker-compose.yml
  internal/server/audit/kafka/avro.go
  internal/server/audit/kafka/encoding_test.go
  internal/server/audit/kafka/kafka.go
Labels: size:L

#3812 chore: Prep 1.54.2
  .github/images/flipt-cloud.svg
  .github/workflows/release.yml
  .goreleaser.yml
  CHANGELOG.md
  README.md
  _tools/go.mod
  _tools/go.sum
  build/Dockerfile
  build/go.mod
  build/go.sum
  core/go.mod
  core/go.sum
  examples/basic/go.mod
  examples/basic/go.sum
  examples/openfeature/go.mod
  examples/openfeature/go.sum
  go.mod
  go.sum
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/storage/fs/object/store.go
  internal/storage/fs/object/store_test.go
  internal/storage/fs/store/store.go
  rpc/flipt/analytics/analytics.pb.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/options/options.pb.go
  sdk/go/go.mod
  sdk/go/go.sum
  ui/package-lock.json
  ui/package.json
  ui/src/app/Layout.tsx
  ui/src/app/Onboarding.tsx
  ui/src/app/events/eventSlice.ts
  ui/src/components/Banner.tsx
  ui/tests/onboarding.spec.ts
Labels: size:L

#3833 chore: add note about v2 development
  README.md
Labels: automerge, size:S

#3834 feat(rpc): initial prototype for the v2 environments API
  buf.gen.yaml
  buf.lock
  buf.work.yaml
  buf.yaml
  go.mod
  go.sum
  go.work
  go.work.sum
  magefile.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/buf.gen.yaml
  rpc/flipt/buf.lock
  rpc/flipt/core/core.pb.go
  rpc/flipt/core/core.proto
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/flipt.pb.gw.go
  rpc/flipt/flipt.proto
  rpc/flipt/flipt.yaml
  rpc/flipt/flipt_grpc.pb.go
  rpc/flipt/marshaller.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/request.go
  rpc/flipt/request_test.go
  rpc/flipt/scoped.go
  rpc/flipt/validation.go
  rpc/flipt/validation_fuzz_test.go
  rpc/flipt/validation_test.go
  rpc/v2/environments/buf.gen.yaml
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.pb.gw.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/environments.yaml
  rpc/v2/environments/environments_grpc.pb.go
  rpc/v2/environments/go.mod
  rpc/v2/environments/go.sum
  rpc/v2/environments/request.go
  rpc/v2/environments/validation.go
  sdk/go/flipt.sdk.gen.go
  sdk/go/http/flipt.sdk.gen.go
Labels: size:XXL

#3836 chore: add storage/env configuration and update tests
  PLAN.md
  README.md
  examples/tracing/README.md
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/config/analytics.go
  internal/config/authentication.go
  internal/config/authentication_test.go
  internal/config/authorization.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/cors.go
  internal/config/environments.go
  internal/config/errors.go
  internal/config/metrics.go
  internal/config/server.go
  internal/config/storage.go
  internal/config/storage_test.go
  internal/config/testdata/advanced.yml
  internal/config/testdata/database/missing_host.yml
  internal/config/testdata/database/missing_name.yml
  internal/config/testdata/database/missing_protocol.yml
  internal/config/testdata/environments/missing_name.yml
  internal/config/testdata/environments/no_matching_storage.yml
  internal/config/testdata/marshal/yaml/default.yml
  internal/config/testdata/storage/git_basic_auth_invalid.yml
  internal/config/testdata/storage/git_invalid_ref_type.yml
  internal/config/testdata/storage/git_provided.yml
  internal/config/testdata/storage/git_provided_with_backend_type.yml
  internal/config/testdata/storage/git_provided_with_directory.yml
  internal/config/testdata/storage/git_provided_with_ref_type.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_missing_password.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_private_key_both.yml
  internal/config/testdata/storage/git_ssh_auth_invalid_private_key_missing.yml
  internal/config/testdata/storage/git_ssh_auth_valid_with_path.yml
  internal/config/testdata/storage/invalid_git_repo_not_specified.yml
  internal/config/testdata/storage/invalid_readonly.yml
  internal/config/testdata/storage/local_provided.yml
  internal/config/tracing.go
  internal/config/ui.go
  internal/info/flipt.go
  internal/info/flipt_test.go
  internal/storage/fs/store/store.go
  internal/telemetry/telemetry.go
Labels: size:XXL

#3851 refactor(internal/server): remove unused server implementations and remove v2 folder
  internal/server/environments/server.go
  internal/server/environments/storage.go
  internal/server/flag.go
  internal/server/namespace.go
  internal/server/namespace_test.go
  internal/server/rollout.go
  internal/server/rollout_test.go
  internal/server/rule.go
  internal/server/rule_test.go
  internal/server/segment.go
  internal/server/segment_test.go
Labels: size:XXL

#3852 feat: V2 authn config + redis
  cmd/flipt/evaluate.go
  cmd/flipt/main.go
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/config/authentication.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/errors.go
  internal/server/authn/method/github/server_test.go
  internal/server/authn/method/http.go
  internal/server/authn/method/kubernetes/server_internal_test.go
  internal/server/authn/method/kubernetes/server_test.go
  internal/server/authn/method/kubernetes/testing/grpc.go
  internal/server/authn/method/oidc/server_test.go
  internal/server/authn/method/oidc/testing/grpc.go
  internal/server/authn/method/token/server_test.go
  internal/server/authn/middleware/grpc/middleware_test.go
  internal/server/authn/middleware/http/middleware.go
  internal/server/authn/middleware/http/middleware_test.go
  internal/server/authn/public/server_test.go
  internal/server/authn/server_test.go
  internal/storage/authn/auth.go
  internal/storage/authn/bootstrap.go
  internal/storage/authn/bootstrap_test.go
  internal/storage/authn/memory/store.go
  internal/storage/authn/memory/store_test.go
  internal/storage/authn/redis/client.go
  internal/storage/authn/redis/client_test.go
  internal/storage/authn/redis/store.go
  internal/storage/authn/redis/store_test.go
  internal/storage/authn/testing/testing.go
  internal/storage/oplock/memory/memory.go
  internal/storage/oplock/memory/memory_test.go
  internal/storage/oplock/oplock.go
  internal/storage/oplock/testing/testing.go
  internal/telemetry/telemetry_test.go
Labels: size:XXL

#3853 fix: apply UI additional http headers only for requests to UI assets
  internal/cmd/http.go
Labels: size:S

#3857 fix(ui): ui.topbar.color config setting has been broken since v1.53.0
  ui/src/app/meta/metaSlice.ts
Labels: automerge, size:XS

#3858 fix: wire up evaluation state using new environments abstraction
  cmd/flipt/validate.go
  go.work.sum
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/config/authentication.go
  internal/server/authz/middleware/grpc/middleware.go
  internal/server/authz/middleware/grpc/middleware_test.go
  internal/server/environments/server.go
  internal/server/environments/storage.go
  internal/server/evaluation/data/evaluation_store_mock.go
  internal/server/evaluation/data/server.go
  internal/server/evaluation/data/server_test.go
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_store_mock.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/ofrep_bridge.go
  internal/server/evaluation/ofrep_bridge_test.go
  internal/server/evaluation/server.go
  internal/storage/authn/memory/store.go
  internal/storage/authn/static/store.go
  internal/storage/authn/static/store_test.go
  internal/storage/authn/testing/testing.go
  internal/storage/environments/evaluation/publisher.go
  internal/storage/environments/evaluation/snapshot.go
  internal/storage/environments/fs/environment.go
  internal/storage/environments/git/store.go
  internal/storage/fs/snapshot.go
  internal/storage/storage.go
  rpc/flipt/core/core.pb.go
  rpc/flipt/core/core.proto
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.proto
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.proto
Labels: size:XXL

#3856 chore: use Grpc inproc
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/go.mod
  build/go.sum
  build/main.go
  build/testing/integration/api/api.go
  build/testing/integration/authn/auth.go
  build/testing/integration/authz/auth.go
  build/testing/integration/integration.go
  build/testing/integration/ofrep/ofrep_test.go
  build/testing/integration/readonly/readonly_test.go
  build/testing/integration/snapshot/snapshot_test.go
  build/testing/loadtest.go
  cmd/flipt/main.go
  dagger.json
  go.mod
  go.sum
  go.work.sum
  internal/cmd/authn.go
  internal/cmd/grpc.go
  internal/cmd/grpc_test.go
  internal/cmd/http.go
  internal/server/evaluation/data/server.go
  internal/server/evaluation/data/server_test.go
Labels: automerge, size:XXL
