Repository flipt-io/flipt, pull requests merged in 2025-09, with the labels that each got.

#4678 fix: allow rollout and percentage zero values in YAML serialization
  core/validation/testdata/valid_zero_values.yaml
  core/validation/validate_test.go
  internal/ext/common.go
  internal/ext/common_test.go
Labels: automerge, size:L, v2

#4683 chore: prep for v2.1.0 release
  CHANGELOG.md
  go.work.sum
Labels: size:S

#4708 docs: add rohitnarayan as a contributor for code
  .all-contributorsrc
Labels: automerge, size:XS, v1

#4723 chore: prep Release/1.60
  CHANGELOG.md
  go.work.sum
Labels: size:S

#4746 chore: remove toolchain in go.mod files as renovate fails with it. set go directives to 1.25
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/go.mod
  build/go.sum
  core/go.mod
  core/go.sum
  errors/go.mod
  go.work.sum
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/core/core.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/flipt.pb.go
  rpc/flipt/go.mod
  rpc/flipt/go.sum
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/options/options.pb.go
  rpc/v2/analytics/analytics.pb.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/go.mod
  rpc/v2/environments/go.sum
  rpc/v2/evaluation/evaluation.pb.go
  rpc/v2/evaluation/go.mod
  rpc/v2/evaluation/go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/v2/go.mod
  sdk/go/v2/go.sum
Labels: size:L

#4747 chore: update changelog for 2.1.1
  CHANGELOG.md
Labels: size:S

#4753 fix(auth): allow to exclude auth for ofrep endpoint
  go.work.sum
  internal/cmd/grpc.go
Labels: automerge, size:XS

#4754 chore: bump changelog for 2.1.2 release
  CHANGELOG.md
Labels: size:S

#4764 fix: read CHANGELOG.md from tagged commit during release
  .github/prompts/release.md
Labels: size:XS

#4766 fix(evaluation): add segments to the boolean evaluation response
  internal/server/evaluation/evaluation.go
  internal/server/evaluation/evaluation_test.go
  internal/server/evaluation/ofrep_bridge.go
  rpc/flipt/audit/event.pb.go
  rpc/flipt/auth/auth.pb.go
  rpc/flipt/core/core.pb.go
  rpc/flipt/evaluation/evaluation.pb.go
  rpc/flipt/evaluation/evaluation.proto
  rpc/flipt/flipt.pb.go
  rpc/flipt/meta/meta.pb.go
  rpc/flipt/ofrep/ofrep.pb.go
  rpc/flipt/openapi.yaml
  rpc/flipt/options/options.pb.go
  rpc/v2/analytics/analytics.pb.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/evaluation/evaluation.pb.go
Labels: size:M, v2

#4767 feat: add flipt license CLI command with TUI wizard
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  AGENTS.md
  CLAUDE.md
  build/go.mod
  build/go.sum
  cmd/flipt/DESIGN.md
  cmd/flipt/license.go
  cmd/flipt/main.go
  cmd/flipt/quickstart.go
  cmd/flipt/styles.go
  dagger.json
  go.mod
  go.sum
  go.work.sum
  internal/coss/license/license.go
  internal/otel/resource.go
  internal/otel/resource_test.go
  ui/AGENTS.md
  ui/CLAUDE.md
Labels: size:XXL

#4770 fix(environments): remove deleted branches from UI when synced from Git
  go.work.sum
  internal/server/environments/storage.go
  internal/storage/environments/environments.go
  internal/storage/environments/git/store.go
  internal/storage/environments/git/store_test.go
  internal/storage/git/repository.go
Labels: automerge, size:L, v2

#4776 feat(ci): add automated DCO check comment workflow
  .github/workflows/contributing.yml
Labels: size:L

#4777 fix(ci): correct YAML indentation in comment body
  .github/workflows/contributing.yml
Labels: size:XS
