Repository flipt-io/flipt, pull requests merged in 2025-07, with the labels that each got.

#4412 chore: Update feature_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:XS

#4414 fix: respect X-Environment header in v1 ListFlags endpoint
  internal/cmd/http.go
  internal/server/flag.go
  internal/server/flag_test.go
Labels: size:L

#4415 chore: add modernize mage target, run it, update CLAUDE.md
  CLAUDE.md
  internal/config/config_test.go
  internal/coss/storage/environments/git/github/github.go
  internal/release/check_test.go
  internal/server/authn/method/kubernetes/server_internal_test.go
  internal/server/authn/method/oidc/server_internal_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
  internal/storage/environments/evaluation/publisher.go
  internal/storage/environments/git/store.go
  internal/storage/git/filesystem.go
  magefile.go
Labels: size:M

#4444 fix(authn): github allowed_teams keys are lowercased in configuration
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/authentication/github_case_sensitive.yml
  internal/server/evaluation/client/server_test.go
Labels: size:M, v2

#4447 chore: remove the sandbox section from readme
  README.md
Labels: size:XS

#4429 feat: V2 secrets
  .github/workflows/integration-test.yml
  .mockery.yml
  README.md
  build/testing/integration.go
  build/testing/integration/signing/README.md
  build/testing/integration/signing/signing_test.go
  build/testing/integration/testdata/environments/README.md
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/cmd/grpc.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/secrets.go
  internal/config/secrets_test.go
  internal/config/storage.go
  internal/config/testdata/secrets/file_provider.yml
  internal/config/testdata/secrets/file_provider_missing_base_path.yml
  internal/config/testdata/secrets/multiple_providers.yml
  internal/config/testdata/secrets/vault_provider.yml
  internal/config/testdata/secrets/vault_provider_missing_address.yml
  internal/config/testdata/secrets/vault_provider_missing_role_approle.yml
  internal/config/testdata/secrets/vault_provider_missing_role_kubernetes.yml
  internal/config/testdata/secrets/vault_provider_missing_token.yml
  internal/config/testdata/secrets/vault_provider_unsupported_auth.yml
  internal/config/testdata/storage/git_signing_enabled.yml
  internal/config/testdata/storage/git_signing_invalid_key_ref_key.yml
  internal/config/testdata/storage/git_signing_invalid_key_ref_path.yml
  internal/config/testdata/storage/git_signing_invalid_key_ref_provider.yml
  internal/config/testdata/storage/git_signing_missing_key_ref.yml
  internal/config/testdata/storage/git_signing_missing_type.yml
  internal/config/testdata/storage/git_signing_unsupported_type.yml
  internal/coss/license/license.go
  internal/coss/license/license_mock.go
  internal/coss/license/license_test.go
  internal/coss/signing/gpg.go
  internal/coss/signing/gpg_test.go
  internal/info/flipt.go
  internal/info/flipt_test.go
  internal/secrets/file/provider.go
  internal/secrets/file/provider_test.go
  internal/secrets/manager.go
  internal/secrets/manager_test.go
  internal/secrets/provider.go
  internal/secrets/secrets_mock.go
  internal/secrets/vault/provider.go
  internal/secrets/vault/provider_test.go
  internal/storage/environments/environments.go
  internal/storage/git/filesystem.go
  internal/storage/git/repository.go
  internal/storage/git/signing/signer.go
  internal/storage/git/signing_test.go
Labels: automerge, needs docs, size:XXL

#4462 fix(ui): invalidate cache after creating merge proposal
  config/dev.yml
  ui/src/app/environments/environmentsApi.ts
Labels: automerge, size:M

#4461 feat(scm): added support for Azure DevOps
  .mockery.yml
  CLAUDE.md
  build/go.mod
  build/go.sum
  build/internal/cmd/gitea/main.go
  cmd/flipt/quickstart.go
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/config/environments.go
  internal/coss/signing/gpg.go
  internal/coss/signing/gpg_test.go
  internal/coss/storage/environments/git/azure/azure.go
  internal/coss/storage/environments/git/azure/azure_mock.go
  internal/coss/storage/environments/git/azure/azure_test.go
  internal/coss/storage/environments/git/gitea/gitea.go
  internal/coss/storage/environments/git/gitea/gitea_test.go
  internal/coss/storage/environments/git/github/github.go
  internal/coss/storage/environments/git/gitlab/gitlab.go
  internal/coss/storage/environments/git/store.go
  internal/coss/storage/environments/git/url.go
  internal/coss/storage/environments/git/url_test.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/storage/environments/environments.go
  internal/storage/environments/git/store.go
  internal/storage/environments/git/store_test.go
  internal/storage/git/filesystem.go
  internal/storage/git/filesystem_test.go
  internal/storage/git/repository.go
  internal/storage/git/signing/signer.go
  internal/storage/git/signing_test.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/openapi.yaml
  ui/src/components/environments/branches/CreateMergeProposalModal.tsx
  ui/src/types/Environment.ts
Labels: automerge, needs docs, size:XXL

#4479 chore(dagger): bump dagger to 0.18.12
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/.gitignore
  build/go.mod
  build/go.sum
  dagger.json
  go.work.sum
Labels: automerge, size:M

#4463 fix(secrets): add base64 decoding fallback for file provider values
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/secrets/file/provider.go
  internal/secrets/file/provider_test.go
Labels: automerge, size:M

#4485 fix: rework Shutdown for license
  internal/coss/license/license.go
  internal/coss/license/license_test.go
Labels: size:M

#4484 refactor(license): simplify license manager and fix potential panics
  internal/coss/license/license.go
  internal/coss/license/license_test.go
Labels: size:L

#4486 fix(license): resolve timeout issues during license deactivation on shutdown
  cmd/flipt/main.go
  internal/coss/license/license.go
Labels: size:XS

#4487 feat(license): add support for offline license validation
  cmd/flipt/main.go
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/config/config.go
  internal/config/config_test.go
  internal/config/license.go
  internal/config/testdata/license/invalid_file_no_key.yml
  internal/config/testdata/license/invalid_file_not_found.yml
  internal/config/testdata/license/valid_with_key_and_file.yml
  internal/config/testdata/license/valid_with_key_only.yml
  internal/coss/license/license.go
  internal/coss/license/license_test.go
Labels: needs docs, size:XL

#4499 fix(ui): variant with no name is not shown in the rules
  ui/src/types/Variant.ts
Labels: size:XS
