Repository flipt-io/flipt, pull requests merged in 2025-03, with the labels that each got.

#3973 docs: Fix typo in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size:XS

#3976 fix(ui): use correct default theme on first load
  ui/src/app/preferences/preferencesSlice.ts
Labels: size:XS

#3975 fix: otel interceptor panic/handling after switch to grpchan
  .github/workflows/lint.yml
  cmd/flipt/main.go
  config/local.yml
  go.work.sum
  internal/cmd/grpc.go
  internal/cmd/http.go
  internal/config/audit.go
  internal/config/audit_test.go
  internal/gateway/gateway.go
  internal/server/audit/cloud/cloud.go
  internal/server/audit/cloud/cloud_test.go
Labels: automerge, size:L

#3982 chore: rm stackhawk
  .github/workflows/nightly.yml
  go.work.sum
  stackhawk.yml
Labels: size:M

#3983 feat: move default boolean value to top; show in flag table view
  ui/src/assets/colors/dark.css
  ui/src/components/Badge.tsx
  ui/src/components/flags/FlagTable.tsx
  ui/src/components/flags/forms/FlagForm.tsx
  ui/src/components/forms/Toggle.tsx
  ui/src/components/rollouts/Rollouts.tsx
  ui/tests/rollouts.spec.ts
Labels: automerge, size:L

#3996 chore: prepare 1.56
  CHANGELOG.md
  go.work.sum
Labels: size:XS

#4002 chore(deps): bump dagger to v0.17.1
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/go.mod
  build/go.sum
  build/internal/ui.go
  build/testing/cli.go
  build/testing/integration.go
  build/testing/migration.go
  build/testing/redpanda.go
  build/testing/test.go
  build/testing/ui.go
  dagger.json
  go.work.sum
Labels: size:L
