Repository flipt-io/flipt, pull requests merged in 2025-08, with the labels that each got.

#4502 chore: Release/1.59.2
  CHANGELOG.md
Labels: size:XS

#4504 fix(ui): remove rounded border in header
  ui/src/components/Header.tsx
Labels: size:XS

#4506 fix: resolve fuzz test failures causing stack overflow
  internal/coss/signing/gpg_fuzz_test.go
  internal/coss/storage/environments/git/url_fuzz_test.go
  internal/storage/fs/config.go
  internal/storage/fs/config_fuzz_test.go
  internal/storage/fs/snapshot_fuzz_test.go
Labels: size:XL

#4519 feat: fix integration test coverage collection and consolidate Dagger build functions
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  build/internal/flipt.go
  build/internal/ui.go
  build/main.go
  build/testing/integration.go
  codecov.yml
Labels: automerge, size:XL

#4520 feat: optimize UI integration tests with cached Flipt images
  .github/workflows/integration-test.yml
Labels: automerge, size:S

#4521 feat: add BitBucket SCM support for v2 environment pull requests
  .golangci.yml
  .mockery.yml
  cmd/flipt/quickstart.go
  go.mod
  go.sum
  go.work.sum
  internal/config/config_test.go
  internal/config/environments.go
  internal/coss/secrets/vault/provider.go
  internal/coss/signing/gpg.go
  internal/coss/storage/environments/git/azure/azure.go
  internal/coss/storage/environments/git/azure/azure_test.go
  internal/coss/storage/environments/git/bitbucket/bitbucket.go
  internal/coss/storage/environments/git/bitbucket/bitbucket_mock.go
  internal/coss/storage/environments/git/bitbucket/bitbucket_test.go
  internal/coss/storage/environments/git/gitea/gitea.go
  internal/coss/storage/environments/git/gitea/gitea_test.go
  internal/coss/storage/environments/git/github/github.go
  internal/coss/storage/environments/git/github/github_test.go
  internal/coss/storage/environments/git/gitlab/gitlab.go
  internal/coss/storage/environments/git/gitlab/gitlab_test.go
  internal/coss/storage/environments/git/url_test.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/storage/environments/environments.go
  internal/storage/environments/environments_test.go
  internal/storage/environments/git/store.go
  internal/storage/environments/git/store_test.go
  rpc/v2/environments/environments.pb.go
  rpc/v2/environments/environments.proto
  rpc/v2/environments/openapi.yaml
  ui/src/types/Environment.ts
Labels: automerge, needs docs, size:XXL, v2

#4524 fix: allow integration tests to run for PRs from forks
  .github/workflows/integration-test.yml
Labels: size:M

#4522 Introduce configurable mapping of jwt claims to well known authentica…
  config/flipt.schema.cue
  config/flipt.schema.json
  go.mod
  go.sum
  go.work.sum
  internal/cmd/authn.go
  internal/config/authentication.go
  internal/config/authentication_test.go
  internal/server/authn/middleware/grpc/middleware.go
  internal/server/authn/middleware/grpc/middleware_test.go
Labels: automerge, size:L

#4546 chore: rm outdated dev instructions, update devenv
  .github/images/devenv.png
  .gitpod.yml
  DEVELOPMENT.md
  devenv.lock
  devenv.nix
  render.yaml
Labels: size:M

#4545 feat: remove jq dependency from v2 install script
  install.sh
Labels: automerge, size:M

#4552 chore(deps): use go-git/go-billy/v6 instead of v5
  core/validation/validate.go
  go.mod
  go.sum
  go.work.sum
  internal/storage/environments/osfs/osfs.go
Labels: automerge, size:S

#4553 fix: install script incorrectly installing beta versions
  .github/workflows/lint.yml
  .github/workflows/test.yml
  install.sh
Labels: bug, size:L, v2

#4557 docs: clean up Development.md
  DEVELOPMENT.md
  Dockerfile
Labels: size:M

#4559 chore: add claude.md for ui subfolder
  ui/CLAUDE.md
Labels: automerge, size:L

#4558 chore(deps): bump go from 1.24 to 1.25
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/nightly.yml
  .github/workflows/proto.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CLAUDE.md
  DEVELOPMENT.md
  Dockerfile.dev
  build/internal/flipt.go
  build/main.go
  build/testing/integration.go
  go.mod
  go.sum
  go.work
  go.work.sum
  internal/cmd/grpc.go
  internal/cmd/protoc-gen-go-flipt-sdk/go.mod
  internal/cmd/protoc-gen-go-flipt-sdk/go.sum
  internal/cmd/util/browser.go
  internal/server/analytics/clickhouse/client.go
Labels: size:L

#4562 fix: include type and enabled flag attributes for v1 ListFlags api call
  internal/server/flag.go
  internal/server/flag_test.go
Labels: automerge, size:M, v2

#4564 fix: rm hanging test; add x-flipt-accept-server-version to default cors headers
  config/flipt.schema.cue
  config/flipt.schema.json
  internal/config/config.go
  internal/config/cors.go
  internal/storage/environments/environments_test.go
Labels: automerge, size:M, v2

#4565 chore: update changelog for 2.0.1
  CHANGELOG.md
Labels: size:S

#4592 chore: Add renovate
  .github/renovate.json5
Labels: size:M

#4604 chore: add back homebrew config for release; try generating release notes with ai
  .github/prompts/release.md
  .goreleaser.yml
Labels: automerge, size:M

#4605 chore: bump changelog for 2.0.2
  .github/prompts/release.md
  .github/workflows/release.yml
  CHANGELOG.md
Labels: size:M

#4607 feat(ui): add Flipt v2 release banner and fix command dialog overlay
  go.work.sum
  internal/server/ofrep/server_test.go
  ui/playwright.config.ts
  ui/src/app/Layout.tsx
  ui/src/app/events/eventSlice.ts
  ui/src/components/Banner.tsx
  ui/src/components/command/CommandDialog.tsx
  ui/src/store.ts
Labels: size:M

#4639 feat: Quickstart tui
  cmd/flipt/quickstart.go
  go.mod
  go.sum
  go.work.sum
Labels: size:XXL

#4660 feat(ui): add Flipt Pro trial banner
  ui/src/app/Layout.tsx
  ui/src/app/events/eventSlice.ts
  ui/src/components/Banner.tsx
  ui/src/components/ProBanner.tsx
  ui/src/store.ts
Labels: size:L

#4666 chore: add bitbucket to scm schema
  config/flipt.schema.cue
  config/flipt.schema.json
Labels: size:XS

#4622 fix: handle empty directories correctly during namespace deletion
  internal/storage/git/filesystem.go
  internal/storage/git/filesystem_test.go
Labels: size:L

#4661 refactor(ui): consolidate UI components into main components directory
  ui/CLAUDE.md
  ui/src/app/Layout.tsx
  ui/src/app/auth/Login.tsx
  ui/src/components/AppSidebar.tsx
  ui/src/components/Avatar.tsx
  ui/src/components/BaseInput.tsx
  ui/src/components/Button.tsx
  ui/src/components/DropdownMenu.tsx
  ui/src/components/Header.tsx
  ui/src/components/NavMain.tsx
  ui/src/components/NavSecondary.tsx
  ui/src/components/NavUser.tsx
  ui/src/components/Separator.tsx
  ui/src/components/Sheet.tsx
  ui/src/components/Sidebar.tsx
  ui/src/components/Skeleton.tsx
  ui/src/components/Tooltip.tsx
  ui/src/components/environments/EnvironmentNamespaceSwitcher.tsx
  ui/src/components/environments/branches/BranchActionsDropdown.tsx
  ui/src/components/environments/branches/CreateBranchPopover.tsx
  ui/src/components/environments/branches/CreateMergeProposalModal.tsx
  ui/src/components/environments/branches/DeleteBranchModal.tsx
  ui/src/components/rules/MultiDistributionForm.tsx
  ui/src/components/ui/button.tsx
  ui/src/components/ui/dropdown-menu.tsx
  ui/src/components/ui/skeleton.tsx
Labels: automerge, size:XL
